More fixups and cleanups

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -79,7 +79,7 @@ ok()
 
 err()
 {
-	say "❌ ${@}"
+	say "❌ ${@}" 1>&@
 }
 
 fail()
@@ -94,10 +94,10 @@ list_versions()
 
 	# There will be symlinks for major, major-minor, etc... so one doesn't have to enter
 	# the full version, as well as "latest" ...
-	/usr/bin/find -L "${TOOL}" -mindepth 1 -maxdepth 1 -type d | \
-		/usr/bin/sed -e 's;/$;;g' -e 's;^.*/;;g' | \
-		/usr/bin/grep -v "${LATEST}" | \
-		/usr/bin/sort -V | while read v ; do
+	find -L "${TOOL}" -mindepth 1 -maxdepth 1 -type d | \
+		sed -e 's;/$;;g' -e 's;^.*/;;g' | \
+		grep -v "${LATEST}" | \
+		sort -V | while read v ; do
 		[ -e "${TOOL}/${v}/${IGNORE}" ] && continue
 		echo "${v}"
 	done
@@ -169,7 +169,7 @@ configure_tools()
 		# The version directory exists, so use it
 
 		# We use readlink -f to resolve the actual path for the tool before configuring it
-		ACTUAL="$(/usr/bin/readlink -f "${TOOL_VERSION}")"
+		ACTUAL="$(readlink -f "${TOOL_VERSION}")"
 
 		# This is the actual version we're using
 		VER="${ACTUAL##*/}"
@@ -182,7 +182,7 @@ configure_tools()
 		TOOL_BIN="${ACTUAL}/bin"
 		[ -d "${TOOL_BIN}" ] && PATHS+=("${TOOL_BIN}")
 		OUT+=("${TOOL}/${VER}/${TOOL_BIN:+bin}")
-	done < <(/usr/bin/find -L "${TOOL_DIR}" -mindepth 1 -maxdepth 1 -type d -not -name bin)
+	done < <(find -L "${TOOL_DIR}" -mindepth 1 -maxdepth 1 -type d -not -name bin)
 
 	if [ ${#ERRORS[@]} -ne 0 ] ; then
 		for E in "${ERRORS[@]}" ; do
@@ -236,9 +236,25 @@ is_mount_supported()
 if [ ! -d "${CACHE_DIR}" ] ; then
 	say "📁 The cache directory [${CACHE_DIR}] does not exist ... creating it!"
 	/usr/bin/sudo -n /usr/bin/mkdir -p "${CACHE_DIR}" || fail "Could not create the cache directory [${CACHE_DIR}]"
-	/usr/bin/sudo -n /usr/bin/chown -R "$(id -u):$(id -g)" "${CACHE_DIR}" || fail "Could not set the ownership for the cache directory"
-	/usr/bin/sudo -n /usr/bin/chmod -R ug=rwX,o= "${CACHE_DIR}" || fail "Could not set the permissions for the cache directory"
 fi
+
+#
+# Make sure the cache is 100% accessible to us
+#
+(
+	set -euo pipefail
+	FIX="false"
+	[ -r "${CACHE_DIR}" ] || FIX="true"
+	[ -w "${CACHE_DIR}" ] || FIX="true"
+	[ -x "${CACHE_DIR}" ] || FIX="true"
+	"${FIX}" || exit 0
+	say "🔐 Ownership and permissions may be off for the cache at [${CACHE_DIR}], fixing them!"
+	say "🔨 Setting ownership..."
+	/usr/bin/sudo -n /usr/bin/chown -R "$(id -u):$(id -g)" "${CACHE_DIR}" || fail "Could not set the ownership for the cache directory"
+	say "🛡️ Setting permissions..."
+	/usr/bin/sudo -n /usr/bin/chmod -R ug=rwX,o= "${CACHE_DIR}" || fail "Could not set the permissions for the cache directory"
+	ok "Cache permissions fixed!"
+) || exit ${?}
 
 #
 # This is a sneaky, sneaky trick we're using to enable us to mount shared filesystems,
@@ -255,7 +271,7 @@ if ! "${DISABLE_COW}" && is_mount_supported ; then
 
 	say "⚙️ Mount is supported, creating the COW mounts for: [${COW_MOUNTS[@]@Q}]"
 	for MOUNTPOINT in "${COW_MOUNTS[@]}"; do
-		MOUNTPOINT="$(/usr/bin/readlink -f "${MOUNTPOINT}")"
+		MOUNTPOINT="$(readlink -f "${MOUNTPOINT}")"
 
 		# First - does the mountpoint exist?
 		if [ ! -d "${MOUNTPOINT}" ] ; then
@@ -283,8 +299,8 @@ if ! "${DISABLE_COW}" && is_mount_supported ; then
 		# Ok... we're good to go on the overlay attempt
 		say "🔩 Creating the overlay for [${MOUNTPOINT}]..."
 
-		/usr/bin/mkdir -p "${WORK}" || fail "Failed to create the work directory [${WORK}]"
-		/usr/bin/mkdir -p "${UPPER}" || fail "Failed to create the upper directory [${UPPER}]"
+		mkdir -p "${WORK}" || fail "Failed to create the work directory [${WORK}]"
+		mkdir -p "${UPPER}" || fail "Failed to create the upper directory [${UPPER}]"
 
 		# Mount the overlay using the above values
 		/usr/bin/sudo -n /usr/bin/mount -t overlay overlay \
@@ -295,9 +311,11 @@ if ! "${DISABLE_COW}" && is_mount_supported ; then
 fi
 
 # Run the tool configurations
+say "🛠️ Configuring the tools"
 CONFIGURED_TOOLS="$(configure_tools)"
 [ ${?} -ne 0 ] && fail "Failed to configure tool versions"
 readarray -t TOOLS < <(echo -n "${CONFIGURED_TOOLS}")
+ok "Tools configured: [${TOOLS[@]@Q}]"
 
 NEW_PATHS=()
 TOOL_NAMES=()
@@ -334,6 +352,7 @@ done
 # We use sanitize_path to end up with a clean path with no duplicate or empty entries
 # We prioritize the new path to give opportunity to override system-default tools
 export PATH="$(sanitize_path "${NEW_PATH}:${PATH}")"
+ok "Added the detected tools to the path: [${PATH}]"
 
 # Finally, source each tool's configuration scripts - version-specific first,
 # then the parent directory's, and finally the overarching configuration script (if any).
@@ -344,19 +363,22 @@ export PATH="$(sanitize_path "${NEW_PATH}:${PATH}")"
 # execution of the parent scripts by setting the IGNORE_PARENT variable to "true". This
 # will cause configuration processing to stop right then and there. These configuration
 # scripts can define more environment variables which will be preserved
+say "⚙️ Configuring the tools: [${TOOL_NAMES[@]@Q}]"
 IGNORE_PARENT=""
 for TOOL in "${TOOL_NAMES[@]}" ; do
-	TOOL_HOME="$(eval echo -n '$'"{${TOOL}_HOME}")"
+	say "🦺 Configuring [${TOOL}]..."
+	TOOL_HOME="${TOOL}_HOME"
+	TOOL_HOME="${!TOOL_HOME}"
 
 	# Tool home is now ${TOOL_DIR}/${TOOL_NAME}/${TOOL_VERSION}, so figure out the values
-	TOOL_VER="$(/usr/bin/basename "${TOOL_HOME}")"
-	TOOL_NAME="$(/usr/bin/basename "$(/usr/bin/dirname "${TOOL_HOME}")")"
+	TOOL_VER="$(basename "${TOOL_HOME}")"
+	TOOL_NAME="$(basename "$(dirname "${TOOL_HOME}")")"
 
 	CFG_PARAMS=()
 	CFG_PARAMS_STACK=("${TOOL_VER}" "${TOOL_NAME}")
 	CANDIDATES=("${TOOL_HOME}" "${TOOL_HOME%/*}" "${TOOL_DIR}")
 	(( i = 0 )) || true
-	pushd "${TOOL_HOME}"
+	pushd "${TOOL_HOME}" &>/dev/null
 	for CANDIDATE in "${CANDIDATES[@]}" ; do
 		# Clear this flag - needs to be done every iteration
 		IGNORE_PARENT=""
@@ -373,14 +395,16 @@ for TOOL in "${TOOL_NAMES[@]}" ; do
 		# it can set the IGNORE_PARENT variable to "true"
 		[ "${IGNORE_PARENT,,}" == "true" ] && break
 	done
-	popd
+	popd &>/dev/null
 done
+ok "Tools configured!"
 
 # Now, we apply any specific configuration files we want to apply. These are generally
 # files that may or may not affect tool execution, but don't really need to be bound
 # to a specific tool, nor tied to a specific init script.
+say "⚙️ Running the global configuration scripts"
 while read CONF ; do
-	CONF_NAME="$(/usr/bin/basename "${CONF}")"
+	CONF_NAME="$(basename "${CONF}")"
 
 	# If it's not accessible, skip it ...
 	[ -r "${CONF}" ] || { say "🚫 Configuration [${CONF_NAME}] is not readable, skipping." ; continue ; }
@@ -389,25 +413,25 @@ while read CONF ; do
 	# If it's to be ignored, do so ...
 	[ -e "${CONF}/${IGNORE}" ] && say "Configuration [${CONF_NAME}] is to be ignored, skipping." && continue
 
-	pushd "${CONF}"
+	pushd "${CONF}" &>/dev/null
 	say "⚙️ Deploying the configurations from [${CONF_NAME}] into [${HOME}]..."
-	/usr/bin/tar -C "${HOME}" -xvf <(/usr/bin/tar --exclude "./${CONFIG}" -cf - .)
+	tar -C "${HOME}" -xvf <(tar --exclude "./${CONFIG}" -cf - .) || fail "Failed to transfer the configurations from ${CONF}"
 	if [ -e "${CONFIG}" ] ; then
 		# The configuration script exists. So execute it
-		say "\t📝 Configuration [${CONF_NAME}] has a script, sourcing it..."
+		say "\t🦺 Configuration [${CONF_NAME}] has a script, sourcing it..."
 		CONFIGURE_SCRIPT="$(readlink -e "${CONFIG}")"
 		[ ${?} -eq 0 ] || fail "Failed to canonicalize the path for [${CONF}/${CONFIG}]"
-		pushd "${HOME}"
+		pushd "${HOME}" &>/dev/null
 		. "${CONFIGURE_SCRIPT}" || fail "Failed to source the configuration script for [${CONF_NAME}]"
-		popd
+		popd &>/dev/null
 	fi
-	popd
-done < <(/usr/bin/find "${CONF_DIR}" -mindepth 1 -maxdepth 1 -type d)
+	popd &>/dev/null
+done < <(find "${CONF_DIR}" -mindepth 1 -maxdepth 1 -type d)
 
 # Allow for initialization scripts to be added
 if [ -d "${INIT_DIR}" ] ; then
-	say "📝 Running initializer scripts in [${INIT_DIR}]..."
-	( cd / && /usr/bin/run-parts --report "${INIT_DIR}" )
+	say "🦺 Running initializer scripts in [${INIT_DIR}]..."
+	( cd / && run-parts --report "${INIT_DIR}" )
 fi
 
 if [ ${#} -gt 0 ] ; then
