Added support for global configurations
Also added preparations for more advanced functionality down the road, whereas we'll use COW mounts for the tools and cache directories, such that builds may freely mess with them without modifying the template directories.

diff --git a/entrypoint b/entrypoint
--- a/entrypoint
+++ b/entrypoint
@@ -2,6 +2,8 @@
 
 LATEST="latest"
 CONFIG="configure"
+# For when we choose to use COWs
+#TOOL_DIR="${HOME}/tools"
 TOOL_DIR="/tools"
 INIT_DIR="/init.d"
 
@@ -112,8 +114,41 @@ sanitize_path() {
 		ENTRIES[${entry}]="${entry}"
 	done < <(echo -n "${OLD_PATH}" | tr ':' '\n')
 	echo "${NEW_PATH}"
-
 }
+
+#
+# This next section is meant to provide a means for builds to customize their own copies of the
+# tools and cache directories without affecting the parent versions. However, to make this happen,
+# we have to employ COW functionality that's only available if the container is run in privileged
+# mode, which is generally not very desirable. Once a decision has been reached to use this,
+# this can be uncommented
+#
+#is_privileged_container() {
+#	sudo ip link add dummy0 type dummy &>/dev/null
+#}
+#
+# Mount an overlay folder for tools and cache?
+#COWS=("tools" "cache")
+#for D in "${COWS[@]}"; do
+#	say "Creating the overlay for [${D}]..."
+#
+#	LOWER="/${D}"
+#	[ -d "${LOWER}" ] || mkdir -p "${LOWER}" || fail "Failed to create the lower directory [${LOWER}]"
+#
+#	UPPER="${HOME}/.${D}"
+#	[ -d "${UPPER}" ] || mkdir -p "${UPPER}" || fail "Failed to create the upper directory [${UPPER}]"
+#
+#	WORK="${HOME}/.work/${D}"
+#	[ -d "${WORK}" ] || mkdir -p "${WORK}" || fail "Failed to create the work directory [${WORK}]"
+#
+#	MERGED="${HOME}/${D}"
+#	[ -d "${MERGED}" ] || mkdir -p "${MERGED}" || fail "Failed to create the overlay directory [${MERGED}]"
+#
+#	# Mount the overlay using the above values
+#	sudo mount -t overlay overlay \
+#		-o lowerdir="${LOWER}",upperdir="${UPPER}",workdir="${WORK}" \
+#		"${MERGED}" || fail "Failed to mount the overlay for [${D}]"
+#done
 
 # Run the tool configurations
 CONFIGURED_TOOLS="$(configure_tools)"
@@ -121,6 +156,7 @@ CONFIGURED_TOOLS="$(configure_tools)"
 readarray -t TOOLS < <(echo -n "${CONFIGURED_TOOLS}")
 
 NEW_PATHS=()
+TOOL_NAMES=()
 TOOL_HOMES=()
 TOOL_VERSIONS=()
 for TOOL in "${TOOLS[@]}" ; do
@@ -129,6 +165,7 @@ for TOOL in "${TOOLS[@]}" ; do
 	TOOL_HOME="${TOOL_DIR}/${tool,,}/${version}"
 	[ -n "${bin}" ] && NEW_PATHS+=("${TOOL_HOME}/bin")
 
+	TOOL_NAMES+=("${tool}")
 	TOOL_HOMES+=("${tool}_HOME=\"${TOOL_HOME}\"")
 	TOOL_VERSIONS+=("${tool}_VER=\"${version}\"")
 done
@@ -155,37 +192,42 @@ done
 export PATH="$(sanitize_path "${NEW_PATH}:${PATH}")"
 
 # Finally, source each tool's configuration scripts - version-specific first,
-# then the parent directory's. We do this after the other configurations complete
-# in the event that tools need to talk to each others
-for TOOL_HOME in "${TOOL_HOMES[@]}" ; do
-	# Clear this flag - needs to be done every iteration
-	IGNORE_PARENT=""
+# then the parent directory's, and finally the overarching configuration script (if any).
+# We do this after the other configurations complete in the event that tools need to talk
+# to each other. Furthermore, each script is told via parameters what it's configuring -
+# be it the version of the tool (for the tool-level script), or even the name of the tool
+# and the version (for the top-level script). Each configuration script can nix the
+# execution of the parent scripts by setting the IGNORE_PARENT variable to "true". This
+# will cause configuration processing to stop right then and there. These configuration
+# scripts can define more environment variables which will be preserved
+IGNORE_PARENT=""
+for TOOL in "${TOOL_NAMES[@]}" ; do
+	TOOL_HOME="$(eval echo -n '$'"{${TOOL}_HOME}")"
 
-	# We're applying the version's configuration file, so let's do it!
-	CFG="${TOOL_HOME}/${CONFIG}"
-	if [ -f "${CFG}" ]; then
-		. "${CFG}" || fail "Failed to apply the configurations from [${CFG}] ..."
-		# If this script wants the parent configuration script to be ignored
+	# Tool home is now ${TOOL_DIR}/${TOOL_NAME}/${TOOL_VERSION}, so figure out the values
+	TOOL_VER="$(basename "${TOOL_HOME}")"
+	TOOL_NAME="$(basename "$(dirname "${TOOL_HOME}")")"
+
+	CFG_PARAMS=()
+	CFG_PARAMS_STACK=("${TOOL_VER}" "${TOOL_NAME}")
+	CANDIDATES=("${TOOL_HOME}" "${TOOL_HOME%/*}" "${TOOL_DIR}")
+	(( i = 0 ))
+	for CANDIDATE in "${CANDIDATES[@]}" ; do
+		# Clear this flag - needs to be done every iteration
+		IGNORE_PARENT=""
+
+		# Seek out the candidate script
+		CFG="${CANDIDATE}/${CONFIG}"
+		if [ -f "${CFG}" ]; then
+			. "${CFG}" "${CFG_PARAMS[@]}" || fail "Failed to apply the configurations from [${CFG}] for [${CFG_PARAMS[@]}] ..."
+		fi
+		CFG_PARAMS=("${CFG_PARAMS_STACK[${i}]}" "${CFG_PARAMS[@]}")
+		(( i++ ))
+
+		# If this script wants the parent configuration script(s) to be ignored
 		# it can set the IGNORE_PARENT variable to "true"
-	fi
-
-	# If we've been told to ignore the parent configuration file, we do so
-	[ "${IGNORE_PARENT,,}" != "true" ] && continue
-
-	# Who's the parent?
-	TOOL_PARENT="${TOOL_HOME%/*}"
-
-	# We're applying the parent configuration file, so let's do it!
-	CFG="${TOOL_PARENT}/${CONFIG}"
-	if [ -f "${CFG}" ]; then
-		. "${CFG}" || fail "Failed to apply the configurations from [${CFG}] ..."
-	fi
-
-	# Allow for global configurations for all tools
-	CFG="${TOOL_DIR}/${CONFIG}"
-	if [ -f "${CFG}" ]; then
-		. "${CFG}" || fail "Failed to apply the configurations from [${CFG}] ..."
-	fi
+		[ "${IGNORE_PARENT,,}" == "true" ] && break
+	done
 done
 
 # Allow for initialization scripts to be added
