Small safeguard to avoid accidental termination

diff --git a/scripts/await-environment b/scripts/await-environment
--- a/scripts/await-environment
+++ b/scripts/await-environment
@@ -59,5 +59,5 @@ if [ ${RC} -eq 0 ] ; then
 else
 	err "Timed out waiting for the deployment to compete boot-up (rc=${RC}), please review the pod logs"
 fi
-execute kubectl --namespace "${NAMESPACE}" get pods
+execute kubectl --namespace "${NAMESPACE}" get pods || err "Failed to produce the pod listing (rc=${?})"
 exit ${RC}
