Updated to use the latest shared functions

diff --git a/scripts/create-k8s-pull-secret b/scripts/create-k8s-pull-secret
--- a/scripts/create-k8s-pull-secret
+++ b/scripts/create-k8s-pull-secret
@@ -4,34 +4,7 @@ BASEDIR="$(dirname "${SCRIPT}")"
 SCRIPT="$(basename "${SCRIPT}")"
 
 set -euo pipefail
-
-timestamp()
-{
-	date -Ins -u
-}
-
-say()
-{
-	echo -e "$(timestamp): ${@}"
-}
-
-err()
-{
-	say "❌ ${@}"
-}
-
-fail()
-{
-	err "${@}"
-	exit ${EXIT_CODE:-1}
-}
-
-is_valid_name()
-{
-	local STR="${1}"
-	[[ "${STR}" =~ ^[a-z0-9]([a-z0-9-]*[a-z0-9])?$ ]] || return 1
-	return 0
-}
+. /.functions
 
 usage()
 {
@@ -48,20 +21,20 @@ else
 	NAMESPACE="${1}"
 	shift
 fi
-is_valid_name "${NAMESPACE}" || fail "Invalid namespace name [${NAMESPACE}]"
+is_valid_hostname_part "${NAMESPACE}" || fail "Invalid namespace name [${NAMESPACE}]"
 
 SECRET_NAME="${1}"
-is_valid_name "${SECRET_NAME}" || fail "The secret name [${SECRET_NAME}] is invalid"
+is_valid_hostname_part "${SECRET_NAME}" || fail "The secret name [${SECRET_NAME}] is invalid"
 
 [ -v DOCKER_CONFIG ] || DOCKER_CONFIG=""
 [ -n "${DOCKER_CONFIG}" ] || DOCKER_CONFIG="${HOME}/.docker"
 
-say "👉 Docker configuration expected at [${DOCKER_CONFIG}]"
+doing "Docker configuration expected at [${DOCKER_CONFIG}]"
 DOCKER_CONFIG="$(readlink -f "${DOCKER_CONFIG}")" || fail "Failed to canonicalize the docker configuration path"
 DOCKER_CONFIG+="/config.json"
 [ -f "${DOCKER_CONFIG}" ] || fail "No docker login configuration available at [${DOCKER_CONFIG}] - cannot continue!"
 
-say "👉 Creating the Kubernetes secret ${SECRET_NAME} in namespace ${NAMESPACE}"
+doing "Creating the Kubernetes secret ${SECRET_NAME} in namespace ${NAMESPACE}"
 kubectl get node &>/dev/null || fail "No access to the K8s cluster, cannot continue"
 
 # Ensure the namespace exists
@@ -69,7 +42,7 @@ kubectl get namespace "${NAMESPACE}" &>/dev/null || \
 	kubectl create namespace "${NAMESPACE}" || \
 	fail "Failed to create the required namespace [${NAMESPACE}]"
 
-say "👉 Creating Kubernetes secret (${SECRET_NAME}) for [${DOCKER_CONFIG}] in namespace [${NAMESPACE}]..."
+doing "Creating Kubernetes secret (${SECRET_NAME}) for [${DOCKER_CONFIG}] in namespace [${NAMESPACE}]..."
 
 # Delete the existing secret, if necessary
 kubectl delete secret \
@@ -84,5 +57,5 @@ kubectl create secret \
 	--from-file=".dockerconfigjson=${DOCKER_CONFIG}" \
 	--type="kubernetes.io/dockerconfigjson" || fail "ERROR: Failed to create the secret ${SECRET_NAME} in namespace ${NAMESPACE} (rc = ${?})"
 
-say "✅ Secret created!"
+ok "Secret created!"
 exit 0
diff --git a/scripts/deploy-environment b/scripts/deploy-environment
--- a/scripts/deploy-environment
+++ b/scripts/deploy-environment
@@ -3,77 +3,19 @@ SCRIPT="$(readlink -f "${BASH_SOURCE:-${0}}")"
 BASEDIR="$(dirname "${SCRIPT}")"
 
 set -euo pipefail
+. /.functions
 
-[ -v DEPLOY_TIMEOUT ] || DEPLOY_TIMEOUT=""
-[ -n "${DEPLOY_TIMEOUT}" ] || DEPLOY_TIMEOUT="20m"
+set_or_default DEPLOY_TIMEOUT "20m"
 
-[ -v DISABLE_DEPLOY ] || DISABLE_DEPLOY=""
-case "${DISABLE_DEPLOY,,}" in
-	true | t | yes | y ) DISABLE_DEPLOY="true" ;;
-	* ) DISABLE_DEPLOY="false" ;;
-esac
+set_as_boolean DISABLE_DEPLOY
 export DISABLE_DEPLOY
 
-[ -v PARTIAL_DEPLOYMENT ] || PARTIAL_DEPLOYMENT="false"
-case "${PARTIAL_DEPLOYMENT,,}" in
-	true | t | yes | y ) PARTIAL_DEPLOYMENT="true" ;;
-	* ) PARTIAL_DEPLOYMENT="false" ;;
-esac
+set_as_boolean PARTIAL_DEPLOYMENT
 export PARTIAL_DEPLOYMENT
-
-timestamp()
-{
-	date -Ins -u
-}
-
-say()
-{
-	echo -e "$(timestamp): ${@}"
-}
-
-warn()
-{
-	say "⚠️ ${@}"
-}
-
-ok()
-{
-	say "✅ ${@}"
-}
-
-err()
-{
-	say "❌ ${@}"
-}
-
-fail()
-{
-	err "${@}"
-	exit ${EXIT_CODE:-1}
-}
-
-is_valid_name()
-{
-	local STR="${1}"
-	[[ "${STR}" =~ ^[a-z0-9]([a-z0-9-]*[a-z0-9])?$ ]] || return 1
-	return 0
-}
 
 execute()
 {
-	#
-	# Show the command about to be executed
-	#
-	say "${@@Q}"
-	if "${DISABLE_DEPLOY}" ; then
-		warn "Deployment disabled: skipping the command execution"
-		return 0
-	fi
-
-	#
-	# Proceed with the execution
-	#
-	( exec "${@}" )
+	execute_conditionally DISABLE_DEPLOY "${@}"
 	return ${?}
 }
 
@@ -206,13 +148,13 @@ else
 	NAMESPACE="${1}"
 	shift
 fi
-is_valid_name "${NAMESPACE}" || fail "Invalid namespace name [${NAMESPACE}]"
+is_valid_hostname_part "${NAMESPACE}" || fail "Invalid namespace name [${NAMESPACE}]"
 
 #
 # The name of the helm release to deploy
 #
 RELEASE="${1}"
-is_valid_name "${RELEASE}" || fail "Invalid release name [${RELEASE}]"
+is_valid_hostname_part "${RELEASE}" || fail "Invalid release name [${RELEASE}]"
 
 #
 # The name of the helm chart to deploy
@@ -224,7 +166,7 @@ CHART="${2}"
 # Ensure we got the right environment n ame
 #
 ENVIRONMENT_NAME="${3}"
-is_valid_name "${ENVIRONMENT_NAME}" || fail "Invalid environment name [${ENVIRONMENT_NAME}]"
+is_valid_hostname_part "${ENVIRONMENT_NAME}" || fail "Invalid environment name [${ENVIRONMENT_NAME}]"
 
 [ -v DEPLOYMENT_DIR ] || DEPLOYMENT_DIR=""
 [ -n "${DEPLOYMENT_DIR}" ] || DEPLOYMENT_DIR="${PWD}"
diff --git a/scripts/downscale-environment b/scripts/downscale-environment
--- a/scripts/downscale-environment
+++ b/scripts/downscale-environment
@@ -3,52 +3,12 @@ SCRIPT="$(readlink -f "${BASH_SOURCE:-${0}}")"
 BASEDIR="$(dirname "${SCRIPT}")"
 
 set -euo pipefail
+. /.functions
 
-[ -v DOWNSCALE_TIMEOUT ] || DOWNSCALE_TIMEOUT=""
-[ -n "${DOWNSCALE_TIMEOUT}" ] || DOWNSCALE_TIMEOUT="20m"
+set_or_default DOWNSCALE_TIMEOUT "20m"
 
-[ -v DISABLE_DOWNSCALE ] || DISABLE_DOWNSCALE=""
-case "${DISABLE_DOWNSCALE,,}" in
-	true | t | yes | y ) DISABLE_DOWNSCALE="true" ;;
-	* ) DISABLE_DOWNSCALE="false" ;;
-esac
+set_as_boolean DISABLE_DOWNSCALE
 export DISABLE_DOWNSCALE
-
-timestamp()
-{
-	date -Ins -u
-}
-
-say()
-{
-	echo -e "$(timestamp): ${@}"
-}
-
-doing()
-{
-	say "👉 ${@}"
-}
-
-ok()
-{
-	say "✅ ${@}"
-}
-
-warn()
-{
-	say "⚠️ ${@}"
-}
-
-err()
-{
-	say "❌ ${@}"
-}
-
-fail()
-{
-	err "${@}"
-	exit ${EXIT_CODE:-1}
-}
 
 is_deployed()
 {
@@ -58,118 +18,10 @@ is_deployed()
 	return ${?}
 }
 
-is_valid_name()
-{
-	local STR="${1}"
-	[[ "${STR}" =~ ^[a-z0-9]([a-z0-9-]*[a-z0-9])?$ ]] || return 1
-	return 0
-}
-
 execute()
 {
-	#
-	# Show the command about to be executed
-	#
-	say "${@@Q}"
-	if "${DISABLE_DOWNSCALE}" ; then
-		warn "Downscaling disabled: skipping the command execution"
-		return 0
-	fi
-
-	#
-	# Proceed with the execution
-	#
-	( exec "${@}" )
+	execute_conditionally DISABLE_DOWNSCALE "${@}"
 	return ${?}
-}
-
-#
-# This function returns the number that serves as
-# a multiplier/divisor for a given time scale
-#
-get_time_mul()
-{
-	local TAG="${1^^}"
-
-	[[ "${TAG}" =~ ^[HDMS]$ ]] || return 1
-	local DURATION_S=1
-	local DURATION_M=$(( DURATION_S * 60 ))
-	local DURATION_H=$(( DURATION_M * 60 ))
-	local DURATION_D=$(( DURATION_H * 24 ))
-
-	local VAR="DURATION_${TAG}"
-	echo -n "${!VAR}"
-}
-
-#
-# This function converts numbers of seconds into
-# K8s timespecs, but leaves timespec strings alone
-#
-secs_to_timestr()
-{
-	local STR="${1}"
-	local NUM="(0|[1-9][0-9]*)"
-
-	[ -n "${STR}" ] || return 1
-
-	# If it's already a time string, return it
-	if [[ "${STR^^}" =~ ^(${NUM}D)?(${NUM}H)?(${NUM}M)?(${NUM}S)?$ ]] ; then
-		echo -n "${STR,,}"
-		return 0
-	fi
-
-	[[ "${STR}" =~ ^${NUM}$ ]] || return 1
-
-	local RET=""
-	local SIZE=0
-	local MUL=0
-	local SECS=${STR}
-	for C in D H M S ; do
-		MUL=$(get_time_mul "${C}")
-		(( SIZE = ( SECS / MUL ) ))
-		[ ${SIZE} -gt 0 ] && RET+="${SIZE}${C}"
-		(( SECS -= ( SIZE * MUL ) ))
-	done
-
-	echo -n ${RET,,}
-	return 0
-}
-
-#
-# This function converts K8s timespecs into
-# numbers of seconds, but leaves numbers alone
-#
-timestr_to_secs()
-{
-	local STR="${1}"
-	local NUM="(0|[1-9][0-9]*)"
-
-	# If it's a straight-up number,
-	# seconds already, so just return it
-	if [[ "${STR}" =~ ^${NUM}$ ]] ; then
-		echo -e "${STR}"
-		return 0
-	fi
-
-	# It could be a time string, so parse it out
-	[ -n "${STR}" ] || return 1
-	[[ "${STR^^}" =~ ^(${NUM}D)?(${NUM}H)?(${NUM}M)?(${NUM}S)?$ ]] || return 1
-
-	local PARTS=( "${BASH_REMATCH[@]:1}" )
-	[ ${#PARTS[@]} -ge 1 ] || return 1
-
-	local SIZE=0
-	local MUL=0
-	local SECS=0
-	for (( i = 0 ; i < ${#PARTS[@]} ; i++ )) ; do
-		[[ "${PARTS[i]}" =~ ^${NUM}([DHMS])$ ]] || continue
-		SIZE=${BASH_REMATCH[1]}
-		MUL=$(get_time_mul "${BASH_REMATCH[2]}")
-		(( SECS += SIZE * MUL ))
-	done
-
-	echo -n ${SECS}
-	return 0
 }
 
 list_scalable_items()
@@ -206,10 +58,10 @@ else
 	NAMESPACE="${1}"
 	shift
 fi
-is_valid_name "${NAMESPACE}" || fail "Invalid namespace name [${NAMESPACE}]"
+is_valid_hostname_part "${NAMESPACE}" || fail "Invalid namespace name [${NAMESPACE}]"
 
 RELEASE="${1}"
-is_valid_name "${RELEASE}" || fail "Invalid release name [${RELEASE}]"
+is_valid_hostname_part "${RELEASE}" || fail "Invalid release name [${RELEASE}]"
 
 # If there's no deployment, do nothing...
 is_deployed "${NAMESPACE}" "${RELEASE}" || fail "The release [${RELEASE}] is not deployed into namespace [${NAMESPACE}] ... can't validate it"
diff --git a/scripts/rancher-ensure-namespace b/scripts/rancher-ensure-namespace
--- a/scripts/rancher-ensure-namespace
+++ b/scripts/rancher-ensure-namespace
@@ -3,39 +3,7 @@ SCRIPT="$(readlink -f "${BASH_SOURCE:-${0}}")"
 BASEDIR="$(dirname "${SCRIPT}")"
 
 set -euo pipefail
-
-timestamp()
-{
-	date -Ins -u
-}
-
-say()
-{
-	echo -e "$(timestamp): ${@}"
-}
-
-warn()
-{
-	say "⚠️ ${@}"
-}
-
-err()
-{
-	say "❌ ${@}"
-}
-
-fail()
-{
-	err "${@}"
-	exit ${EXIT_CODE:-1}
-}
-
-is_valid_name()
-{
-	local STR="${1}"
-	[[ "${STR}" =~ ^[a-z0-9]([a-z0-9-]*[a-z0-9])?$ ]] || return 1
-	return 0
-}
+. /.functions
 
 ensure_namespace_exists()
 {
@@ -54,10 +22,10 @@ usage()
 [ ${#} -eq 3 ] || usage
 
 NAMESPACE="${1}"
-is_valid_name "${NAMESPACE}" || fail "Invalid namespace name [${NAMESPACE}]"
+is_valid_hostname_part "${NAMESPACE}" || fail "Invalid namespace name [${NAMESPACE}]"
 
 CLUSTER_NAME="${2}"
-is_valid_name "${CLUSTER_NAME}" || fail "Invalid cluster name [${CLUSTER_NAME}]"
+is_valid_hostname_part "${CLUSTER_NAME}" || fail "Invalid cluster name [${CLUSTER_NAME}]"
 
 PROJECT_NAME="${3}"
 [ -n "${PROJECT_NAME}" ] || fail "Invalid project name [${PROJECT_NAME}]"
diff --git a/scripts/set-project-version b/scripts/set-project-version
--- a/scripts/set-project-version
+++ b/scripts/set-project-version
@@ -3,12 +3,8 @@ SCRIPT="$(readlink -f "${BASH_SOURCE:-${0}}")"
 BASEDIR="$(dirname "${SCRIPT}")"
 SCRIPT="$(basename "${SCRIPT}")"
 
-FUNCTIONS="${BASEDIR}/.functions"
-if ! . "${FUNCTIONS}" ; then
-	echo -e "ERROR: Failed to load the base functions from [${FUNCTIONS}]"
-	exit 1
-fi
-unset FUNCTIONS
+set -euo pipefail
+. /.functions
 
 usage()
 {
@@ -27,12 +23,12 @@ maven_set_version()
 	local DIR="${2}"
 
 	local POM_XML="${DIR}/pom.xml"
-	check_file "${POM_XML}" || return 0
+	is_file "${POM_XML}" || return 0
 
-	check_dir_readwrite "${DIR}" || fail "The directory [${DIR}] must be readable and writable"
+	require_dir_readwrite "${DIR}"
 	DIR="$(readlink -f "${DIR}")"
 
-	check_file_readwrite "${POM_XML}" || fail "The file [${POM_XML}] must be readable and writable"
+	require_file_readwrite "${POM_XML}"
 
 	say "Setting the POM version number to [${VERSION}] in all relevant files within [${DIR}], recursively ..."
 	local V="$(xmlstarlet sel -N 'p=http://maven.apache.org/POM/4.0.0' -t -v '/p:project/p:version' < "${POM_XML}")"
@@ -55,7 +51,7 @@ nodejs_apply_version()
 	local VERSION="${1}"
 	local JSON="${2}"
 
-	check_file_readwrite "${JSON}" || fail "The JSON file [${JSON}] must be both readable and writable (${?})"
+	require_file_readwrite "${JSON}"
 	say "Processing [${JSON}]"
 	jq --indent 4 --arg VERSION "${VERSION}" '.version = $VERSION' < "${JSON}" > "${BUFFER}" || fail "Failed to render the JSON for [${JSON}] using the new version number [${VERSION}]"
 
@@ -76,7 +72,7 @@ nodejs_list_libraries()
 {
 	local DIR="${1}"
 	local ANGULAR_JSON="${DIR}/angular.json"
-	if ! check_file_readable "${ANGULAR_JSON}" ; then
+	if ! is_file_readable "${ANGULAR_JSON}" ; then
 		err "The file [${ANGULAR_JSON}] must be readable"
 		return 1
 	fi
@@ -92,14 +88,14 @@ nodejs_set_version()
 	local PACKAGE_JSON="package.json"
 
 	local ROOT_PACKAGE_JSON="${DIR}/${PACKAGE_JSON}"
-	check_file "${ROOT_PACKAGE_JSON}" || return 0
+	is_file "${ROOT_PACKAGE_JSON}" || return 0
 
 	say "Setting NodeJS version data"
-	check_dir_readwrite "${DIR}" || fail "The directory [${DIR}] must be readable and writable"
+	require_dir_writable "${DIR}"
 	DIR="$(readlink -f "${DIR}")"
 
 	ROOT_PACKAGE_JSON="${DIR}/${PACKAGE_JSON}"
-	check_file_readwrite "${ROOT_PACKAGE_JSON}" || fail "The file [${ROOT_PACKAGE_JSON}] must be readable and writable"
+	require_file_writable "${ROOT_PACKAGE_JSON}"
 
 	say "Setting the NodeJS version number to [${VERSION}] in all relevant [${PACKAGE_JSON}] files within [${DIR}], recursively ..."
 	say "Setting the NodeJS version on the file [${ROOT_PACKAGE_JSON}]..."
@@ -119,7 +115,7 @@ nodejs_set_version()
 
 trap cleanup EXIT
 
-check_help_flag "${@}" && usage
+is_help_flag "${@}" && usage
 [ ${#} -gt 2 ] && usage
 [ ${#} -lt 1 ] && usage
 
@@ -127,11 +123,11 @@ check_help_flag "${@}" && usage
 [ ${#} -lt 2 ] && set -- "${1}" "."
 
 VERSION="${1}"
-[ -z "${VERSION}" ] && fail "The version may not be the empty string"
+[ -n "${VERSION}" ] || fail "The version may not be the empty string"
 [[ "${VERSION}" =~ [[:space:]] ]] && fail "The version may not contain spaces"
 
 DIR="${2}"
-check_dir_writable "${DIR}" || fail "Can't write to the directory [${DIR}]"
+is_dir_writable "${DIR}" || fail "Can't write to the directory [${DIR}]"
 
 BUFFER="$(mktemp --suffix=.json package.XXXXXXXX)"
 cd "${DIR}" || fail "Failed to CD into [${DIR}]"
diff --git a/scripts/undeploy-environment b/scripts/undeploy-environment
--- a/scripts/undeploy-environment
+++ b/scripts/undeploy-environment
@@ -3,49 +3,15 @@ SCRIPT="$(readlink -f "${BASH_SOURCE:-${0}}")"
 BASEDIR="$(dirname "${SCRIPT}")"
 
 set -euo pipefail
+. /.functions
 
-[ -v UNDEPLOY_TIMEOUT ] || UNDEPLOY_TIMEOUT=""
-[ -n "${UNDEPLOY_TIMEOUT}" ] || UNDEPLOY_TIMEOUT="20m"
+set_or_default UNDEPLOY_TIMEOUT "20m"
 
-[ -v DISABLE_UNDEPLOY ] || DISABLE_UNDEPLOY=""
-case "${DISABLE_UNDEPLOY,,}" in
-	true | t | yes | y ) DISABLE_UNDEPLOY="true" ;;
-	* ) DISABLE_UNDEPLOY="false" ;;
-esac
+set_as_boolean DISABLE_UNDEPLOY
 export DISABLE_UNDEPLOY
 
-[ -v WAIT_FOR_ATTACHMENTS ] || WAIT_FOR_ATTACHMENTS=""
-case "${WAIT_FOR_ATTACHMENTS,,}" in
-	true | t | yes | y ) WAIT_FOR_ATTACHMENTS="true" ;;
-	* ) WAIT_FOR_ATTACHMENTS="false" ;;
-esac
+set_as_boolean WAIT_FOR_ATTACHMENTS
 export WAIT_FOR_ATTACHMENTS
-
-timestamp()
-{
-	date -Ins -u
-}
-
-say()
-{
-	echo -e "$(timestamp): ${@}"
-}
-
-warn()
-{
-	say "⚠️ ${@}"
-}
-
-err()
-{
-	say "❌ ${@}"
-}
-
-fail()
-{
-	err "${@}"
-	exit ${EXIT_CODE:-1}
-}
 
 should_uninstall()
 {
@@ -67,28 +33,9 @@ should_uninstall()
 	esac
 }
 
-is_valid_name()
-{
-	local STR="${1}"
-	[[ "${STR}" =~ ^[a-z0-9]([a-z0-9-]*[a-z0-9])?$ ]] || return 1
-	return 0
-}
-
 execute()
 {
-	#
-	# Show the command about to be executed
-	#
-	say "${@@Q}"
-	if "${DISABLE_UNDEPLOY}" ; then
-		warn "Undeployment disabled: skipping the command execution"
-		return 0
-	fi
-
-	#
-	# Proceed with the execution
-	#
-	( exec "${@}" )
+	execute_conditionally DISABLE_UNDEPLOY "${@}"
 	return ${?}
 }
 
@@ -114,10 +61,10 @@ else
 	NAMESPACE="${1}"
 	shift
 fi
-is_valid_name "${NAMESPACE}" || fail "Invalid namespace name [${NAMESPACE}]"
+is_valid_hostname_part "${NAMESPACE}" || fail "Invalid namespace name [${NAMESPACE}]"
 
 RELEASE="${1}"
-is_valid_name "${RELEASE}" || fail "Invalid release name [${RELEASE}]"
+is_valid_hostname_part "${RELEASE}" || fail "Invalid release name [${RELEASE}]"
 
 # If the target namespace doesn't exist, by extension the environment doesn't exist
 if ! is_namespace_exists "${NAMESPACE}" ; then
@@ -154,7 +101,7 @@ if "${WAIT_FOR_ATTACHMENTS}" ; then
 	true
 
 	# This should help clean up any stragglers
-	if is_valid_name "${SOURCE_CLUSTER:-}" ; then
+	if is_valid_hostname_part "${SOURCE_CLUSTER:-}" ; then
 		DETACHMENT_WAIT_TIMEOUT="${UNDEPLOY_TIMEOUT}" \
 		DISABLE_DETACHMENT_WAIT="${DISABLE_UNDEPLOY}" \
 		"${BASEDIR}/wait-for-volumes-to-detach" "${SOURCE_CLUSTER}" "${NAMESPACE}" "${RELEASE}" || \
diff --git a/scripts/validate-environment b/scripts/validate-environment
--- a/scripts/validate-environment
+++ b/scripts/validate-environment
@@ -3,38 +3,15 @@ SCRIPT="$(readlink -f "${BASH_SOURCE:-${0}}")"
 BASEDIR="$(dirname "${SCRIPT}")"
 
 set -euo pipefail
+. /.functions
 
-[ -v DISABLE_VALIDATE ] || DISABLE_VALIDATE=""
-case "${DISABLE_VALIDATE,,}" in
-	true | t | yes | y ) DISABLE_VALIDATE="true" ;;
-	* ) DISABLE_VALIDATE="false" ;;
-esac
+set_as_boolean DISABLE_VALIDATE
 export DISABLE_VALIDATE
 
-timestamp()
+execute()
 {
-	date -Ins -u
-}
-
-say()
-{
-	echo -e "$(timestamp): ${@}"
-}
-
-warn()
-{
-	say "⚠️ ${@}"
-}
-
-err()
-{
-	say "❌ ${@}"
-}
-
-fail()
-{
-	err "${@}"
-	exit ${EXIT_CODE:-1}
+	execute_conditionally DISABLE_VALIDATE "${@}"
+	return ${?}
 }
 
 is_deployed()
@@ -42,31 +19,6 @@ is_deployed()
 	local NAMESPACE="${1}"
 	local RELEASE="${2}"
 	execute helm get --namespace "${NAMESPACE}" all "${RELEASE}" &>/dev/null
-	return ${?}
-}
-
-is_valid_name()
-{
-	local STR="${1}"
-	[[ "${STR}" =~ ^[a-z0-9]([a-z0-9-]*[a-z0-9])?$ ]] || return 1
-	return 0
-}
-
-execute()
-{
-	#
-	# Show the command about to be executed
-	#
-	say "${@@Q}"
-	if "${DISABLE_VALIDATE}" ; then
-		warn "Deployment disabled: skipping the command execution"
-		return 0
-	fi
-
-	#
-	# Proceed with the execution
-	#
-	( exec "${@}" )
 	return ${?}
 }
 
@@ -85,10 +37,10 @@ else
 	NAMESPACE="${1}"
 	shift
 fi
-is_valid_name "${NAMESPACE}" || fail "Invalid namespace name [${NAMESPACE}]"
+is_valid_hostname_part "${NAMESPACE}" || fail "Invalid namespace name [${NAMESPACE}]"
 
 RELEASE="${1}"
-is_valid_name "${RELEASE}" || fail "Invalid release name [${RELEASE}]"
+is_valid_hostname_part "${RELEASE}" || fail "Invalid release name [${RELEASE}]"
 
 # Delete the old installation, since it's the safest bet to ensure
 # that the correct resources, containers, and deployments are used
diff --git a/scripts/wait-for-volumes-to-detach b/scripts/wait-for-volumes-to-detach
--- a/scripts/wait-for-volumes-to-detach
+++ b/scripts/wait-for-volumes-to-detach
@@ -1,76 +1,16 @@
 #!/bin/bash
 
 set -euo pipefail
+. /.functions
 
-[ -v DETACHMENT_WAIT_TIMEOUT ] || DETACHMENT_WAIT_TIMEOUT=""
-[ -n "${DETACHMENT_WAIT_TIMEOUT}" ] || DETACHMENT_WAIT_TIMEOUT="20m"
+set_or_default DETACHMENT_WAIT_TIMEOUT "20m"
 
-[ -v DISABLE_DETACHMENT_WAIT ] || DISABLE_DETACHMENT_WAIT=""
-case "${DISABLE_DETACHMENT_WAIT,,}" in
-	true | t | yes | y ) DISABLE_DETACHMENT_WAIT="true" ;;
-	* ) DISABLE_DETACHMENT_WAIT="false" ;;
-esac
+set_as_boolean DISABLE_DETACHMENT_WAIT
 export DISABLE_DETACHMENT_WAIT
-
-timestamp()
-{
-	/usr/bin/date -Ins -u
-}
-
-say()
-{
-	echo -e "$(timestamp): ${@}"
-}
-
-ok()
-{
-	say "✅ ${@}"
-}
-
-warn()
-{
-	say "⚠️ ${@}"
-}
-
-err()
-{
-	say "❌ ${@}"
-}
-
-quit()
-{
-	say "🚪 ${@}"
-	exit 0
-}
-
-fail()
-{
-	err "${@}"
-	exit ${EXIT_CODE:-1}
-}
-
-is_valid_name()
-{
-	local NAME="${1}"
-	[[ "${NAME}" =~ ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$ ]] || return 1
-	return 0
-}
 
 execute()
 {
-	#
-	# Show the command about to be executed
-	#
-	say "${@@Q}"
-	if "${DISABLE_DETACHMENT_WAIT}" ; then
-		warn "Attachment waiting disabled: skipping the command execution"
-		return 0
-	fi
-
-	#
-	# Proceed with the execution
-	#
-	( exec "${@}" )
+	execute_conditionally DISABLE_DETACHMENT_WAIT "${@}"
 	return ${?}
 }
 
@@ -147,21 +87,21 @@ usage()
 [ ${#} -eq 3 ] || usage
 
 CLUSTER="${1}"
-is_valid_name "${CLUSTER}" || fail "Invalid Rancher cluster name: [${CLUSTER}]"
+is_valid_hostname_part "${CLUSTER}" || fail "Invalid Rancher cluster name: [${CLUSTER}]"
 
 NAMESPACE="${2}"
-is_valid_name "${NAMESPACE}" || fail "Invalid namespace: [${NAMESPACE}]"
+is_valid_hostname_part "${NAMESPACE}" || fail "Invalid namespace: [${NAMESPACE}]"
 
 RELEASE="${3}"
-is_valid_name "${RELEASE}" || fail "Invalid release name: [${RELEASE}]"
+is_valid_hostname_part "${RELEASE}" || fail "Invalid release name: [${RELEASE}]"
 
 [ -v HARVESTER ] || HARVESTER=""
 [ -n "${HARVESTER}" ] || HARVESTER="harvester-ai5"
-is_valid_name "${HARVESTER}" || fail "Invalid Harvester cluster name: [${HARVESTER}]"
+is_valid_hostname_part "${HARVESTER}" || fail "Invalid Harvester cluster name: [${HARVESTER}]"
 
 [ -v LONGHORN_NAMESPACE ] || LONGHORN_NAMESPACE=""
 [ -n "${LONGHORN_NAMESPACE}" ] || LONGHORN_NAMESPACE="longhorn-system"
-is_valid_name "${LONGHORN_NAMESPACE}" || fail "Invalid Longhorn namespace: [${LONGHORN_NAMESPACE}]"
+is_valid_hostname_part "${LONGHORN_NAMESPACE}" || fail "Invalid Longhorn namespace: [${LONGHORN_NAMESPACE}]"
 
 trap cleanup EXIT
 
