Scripts updated for the new library code

diff --git a/scripts/create-k8s-pull-secret b/scripts/create-k8s-pull-secret
--- a/scripts/create-k8s-pull-secret
+++ b/scripts/create-k8s-pull-secret
@@ -19,22 +19,44 @@ fail() {
 	exit ${EXIT_CODE:-1}
 }
 
+is_valid_name()
+{
+	local STR="${1}"
+	[[ "${STR}" =~ ^[a-z0-9]([a-z0-9-]*[a-z0-9])?$ ]] || return 1
+	return 0
+}
+
+usage()
+{
+	echo -e "usage: ${BASH_SOURCE:-${0}} [namespace] secret-name" 1>&2
+	exit 1
+}
+
 KUBECTL="$(type -P kubectl 2>/dev/null)" || fail "The 'kubectl' executable is not in the path - cannot continue"
 
-[ -v K8S_SECRET ] || K8S_SECRET="aws-arkcase-pull"
-[[ "${K8S_SECRET}" =~ ^[a-zA-Z0-9]([a-zA-Z0-9\-]*[a-zA-Z0-9])?$ ]] || fail "The secret name [${K8S_SECRET}] is invalid"
+[ ${#} -ge 1 ] && [ ${#} -le 2 ] || usage
 
-[ -v NAMESPACE ] || NAMESPACE=""
-[ -n "${NAMESPACE}" ] || NAMESPACE="default"
+if [ ${#} -eq 1 ] ; then
+	NAMESPACE="$("${KUBECTL}" config view --minify -o jsonpath="{..namespace}")"
+	[ -n "${NAMESPACE}" ] || NAMESPACE="default"
+else
+	NAMESPACE="${1}"
+	shift
+fi
+is_valid_name "${NAMESPACE}" || fail "Invalid namespace name [${NAMESPACE}]"
 
-[ -v DOCKER_CONFIG ] || DOCKER_CONFIG="${HOME}/.docker"
+SECRET_NAME="${1}"
+is_valid_name "${SECRET_NAME}" || fail "The secret name [${SECRET_NAME}] is invalid"
+
+[ -v DOCKER_CONFIG ] || DOCKER_CONFIG=""
+[ -n "${DOCKER_CONFIG}" ] || DOCKER_CONFIG="${HOME}/.docker"
+
 say "👉 Docker configuration expected at [${DOCKER_CONFIG}]"
 DOCKER_CONFIG="$(/usr/bin/readlink -f "${DOCKER_CONFIG}")" || fail "Failed to canonicalize the docker configuration path"
 DOCKER_CONFIG+="/config.json"
 [ -f "${DOCKER_CONFIG}" ] || fail "No docker login configuration available at [${DOCKER_CONFIG}] - cannot continue!"
 
-say "👉 Creating the Kubernetes secret ${K8S_SECRET} in namespace ${NAMESPACE}"
-
+say "👉 Creating the Kubernetes secret ${SECRET_NAME} in namespace ${NAMESPACE}"
 "${KUBECTL}" get node &>/dev/null || fail "No access to the K8s cluster, cannot continue"
 
 # Ensure the namespace exists
@@ -42,21 +64,20 @@ say "👉 Creating the Kubernetes secret ${K8S_SECRET} in namespace ${NAMESPACE}
 	"${KUBECTL}" create namespace "${NAMESPACE}" || \
 	fail "Failed to create the required namespace [${NAMESPACE}]"
 
-say "👉 Creating Kubernetes secret (${K8S_SECRET}) for [${DOCKER_CONFIG}] in namespace [${NAMESPACE}]..."
+say "👉 Creating Kubernetes secret (${SECRET_NAME}) for [${DOCKER_CONFIG}] in namespace [${NAMESPACE}]..."
 
 # Delete the existing secret, if necessary
 "${KUBECTL}" delete secret \
 	--namespace "${NAMESPACE}" \
-	"${K8S_SECRET}" &>/dev/null || true
+	"${SECRET_NAME}" &>/dev/null || true
 
 # Create the replacement secret
 "${KUBECTL}" create secret \
 	generic \
 	--namespace "${NAMESPACE}" \
-	"${K8S_SECRET}" \
+	"${SECRET_NAME}" \
 	--from-file=".dockerconfigjson=${DOCKER_CONFIG}" \
-	--type="kubernetes.io/dockerconfigjson" || fail "ERROR: Failed to create the secret ${K8S_SECRET} in namespace ${NAMESPACE} (rc = ${?})"
+	--type="kubernetes.io/dockerconfigjson" || fail "ERROR: Failed to create the secret ${SECRET_NAME} in namespace ${NAMESPACE} (rc = ${?})"
 
-say "\t✅ Secret created!"
-say "✅ Login complete"
+say "✅ Secret created!"
 exit 0
diff --git a/scripts/deploy-environment b/scripts/deploy-environment
--- a/scripts/deploy-environment
+++ b/scripts/deploy-environment
@@ -115,56 +115,58 @@ sanitize_common_dirs()
 	done
 }
 
-add_namespace_to_project()
-{
-	local NAMESPACE="${1}"
-	local CLUSTER_NAME="${2}"
-	local PROJECT_NAME="${3}"
-
-	[ -n "${CLUSTER_NAME}" ] || return 0
-	[ -n "${PROJECT_NAME}" ] || return 0
-
-	execute "${BASEDIR}/rancher-add-ns-to-project" "${NAMESPACE}" "${CLUSTER_NAME}" "${PROJECT_NAME}"
-	return ${?}
-}
-
 usage()
 {
-	echo -e "usage: ${BASH_SOURCE:-${0}} chart environment [extraHelmArgs...]" 1>&2
+	echo -e "usage: ${BASH_SOURCE:-${0}} [namespace] release chart environment [--helm extraHelmArgs...]" 1>&2
 	exit 1
 }
 
-[ ${#} -ge 2 ] || usage
+BASE_ARGS=()
+for a in "${@}" ; do
+	case "${a}" in
+		--helm ) shift ; break ;;
+		* ) BASE_ARGS+=("${a}") ; shift ;;
+	esac
+done
+HELM_ARGS=("${@}")
+
+set -- "${BASE_ARGS[@]}"
+
+[ ${#} -ge 3 ] && [ ${#} -le 4 ] || usage
 
 HELM="$(type -P helm)" || fail "Failed to find helm in the path"
 KUBECTL="$(type -P kubectl)" || fail "Failed to find kubectl in the path"
 
-[ -v NAMESPACE ] || NAMESPACE=""
-[ -n "${NAMESPACE}" ] || NAMESPACE="$("${KUBECTL}" config view --minify -o jsonpath="{..namespace}")"
+if [ "${#}" -eq 3 ] ; then
+	NAMESPACE="$("${KUBECTL}" config view --minify -o jsonpath="{..namespace}")"
+	[ -n "${NAMESPACE}" ] || NAMESPACE="default"
+else
+	NAMESPACE="${1}"
+	shift
+fi
 is_valid_name "${NAMESPACE}" || fail "Invalid namespace name [${NAMESPACE}]"
 
-[ -v RELEASE ] || RELEASE=""
-[ -n "${RELEASE}" ] || RELEASE="arkcase"
+#
+# The name of the helm release to deploy
+#
+RELEASE="${1}"
 is_valid_name "${RELEASE}" || fail "Invalid release name [${RELEASE}]"
-
-[ -v DEPLOYMENT_DIR ] || DEPLOYMENT_DIR=""
-[ -n "${DEPLOYMENT_DIR}" ] || DEPLOYMENT_DIR="${PWD}"
-DEPLOYMENT_DIR="$(/usr/bin/readlink -f "${DEPLOYMENT_DIR}")" || fail "Failed to canonicalize the path for [${DEPLOYMENT_DIR}]"
 
 #
 # The name of the helm chart to deploy
 #
-CHART="${1}"
+CHART="${2}"
 [ -n "${CHART}" ] || fail "The chart name may not be the empty string"
-shift
 
 #
 # Ensure we got the right environment n ame
 #
-ENVIRONMENT_NAME="${1}"
-[ -n "${ENVIRONMENT_NAME}" ] || fail "The environment name may not be the empty string"
+ENVIRONMENT_NAME="${3}"
 is_valid_name "${ENVIRONMENT_NAME}" || fail "Invalid environment name [${ENVIRONMENT_NAME}]"
-shift
+
+[ -v DEPLOYMENT_DIR ] || DEPLOYMENT_DIR=""
+[ -n "${DEPLOYMENT_DIR}" ] || DEPLOYMENT_DIR="${PWD}"
+DEPLOYMENT_DIR="$(/usr/bin/readlink -f "${DEPLOYMENT_DIR}")" || fail "Failed to canonicalize the path for [${DEPLOYMENT_DIR}]"
 
 say "Deploying from [${DEPLOYMENT_DIR}]..."
 [ -f "${DEPLOYMENT_DIR}/deployment.yaml" ] || fail "This does not seem to be a deployment directory - no deployment.yaml was found!"
@@ -231,13 +233,14 @@ else
 fi
 
 ensure_namespace_exists "${NAMESPACE}" || fail "Failed to ensure that the required namespace ${NAMESPACE} exists"
-add_namespace_to_project "${NAMESPACE}" "${CLUSTER_NAME}" "${PROJECT_NAME}" || fail "Failed to apply the project information (${CLUSTER_NAME}:${PROJECT_NAME}) to the namespace ${NAMESPACE}"
 
 # Delete the old installation, since it's the safest bet to ensure
 # that the correct resources, containers, and deployments are used
 #
 # Propagate the "disable" flag, to do nothing if we're testing
 DISABLE_UNDEPLOY="${DISABLE_DEPLOY}" "${BASEDIR}/undeploy-environment" "${NAMESPACE}" "${RELEASE}" || exit ${?}
+
+set -- "${HELM_ARGS[@]}"
 
 # Execute the new installation (we use upgrade b/c we want to future
 # proof this for when we actually do in-place upgrades)
@@ -255,5 +258,5 @@ execute \
 
 # Something went wrong, try to offer up more information
 err "The Helm deployment has failed, please review the logs"
-"${KUBECTL}" --namespace "${NAMESPACE}" get pods
+execute "${KUBECTL}" --namespace "${NAMESPACE}" get pods
 exit ${RC}
