Bump to the newest tools (new Helm), many script cleanups

diff --git a/scripts/create-k8s-pull-secret b/scripts/create-k8s-pull-secret
--- a/scripts/create-k8s-pull-secret
+++ b/scripts/create-k8s-pull-secret
@@ -1,21 +1,28 @@
 #!/bin/bash
-SCRIPT="$(/usr/bin/readlink -f "${BASH_SOURCE:-${0}}")"
-BASEDIR="$(/usr/bin/dirname "${SCRIPT}")"
-SCRIPT="$(/usr/bin/basename "${SCRIPT}")"
+SCRIPT="$(readlink -f "${BASH_SOURCE:-${0}}")"
+BASEDIR="$(dirname "${SCRIPT}")"
+SCRIPT="$(basename "${SCRIPT}")"
 
 set -euo pipefail
 
 timestamp()
 {
-	/usr/bin/date -Ins -u
+	date -Ins -u
 }
 
-say() {
+say()
+{
 	echo -e "$(timestamp): ${@}"
 }
 
-fail() {
-	say "❌ ${@}" 1>&2
+err()
+{
+	say "❌ ${@}"
+}
+
+fail()
+{
+	err "${@}"
 	exit ${EXIT_CODE:-1}
 }
 
@@ -32,12 +39,10 @@ usage()
 	exit 1
 }
 
-KUBECTL="$(type -P kubectl 2>/dev/null)" || fail "The 'kubectl' executable is not in the path - cannot continue"
-
 [ ${#} -ge 1 ] && [ ${#} -le 2 ] || usage
 
 if [ ${#} -eq 1 ] ; then
-	NAMESPACE="$("${KUBECTL}" config view --minify -o jsonpath="{..namespace}")"
+	NAMESPACE="$(kubectl config view --minify -o jsonpath="{..namespace}")"
 	[ -n "${NAMESPACE}" ] || NAMESPACE="default"
 else
 	NAMESPACE="${1}"
@@ -52,27 +57,27 @@ is_valid_name "${SECRET_NAME}" || fail "The secret name [${SECRET_NAME}] is inva
 [ -n "${DOCKER_CONFIG}" ] || DOCKER_CONFIG="${HOME}/.docker"
 
 say "👉 Docker configuration expected at [${DOCKER_CONFIG}]"
-DOCKER_CONFIG="$(/usr/bin/readlink -f "${DOCKER_CONFIG}")" || fail "Failed to canonicalize the docker configuration path"
+DOCKER_CONFIG="$(readlink -f "${DOCKER_CONFIG}")" || fail "Failed to canonicalize the docker configuration path"
 DOCKER_CONFIG+="/config.json"
 [ -f "${DOCKER_CONFIG}" ] || fail "No docker login configuration available at [${DOCKER_CONFIG}] - cannot continue!"
 
 say "👉 Creating the Kubernetes secret ${SECRET_NAME} in namespace ${NAMESPACE}"
-"${KUBECTL}" get node &>/dev/null || fail "No access to the K8s cluster, cannot continue"
+kubectl get node &>/dev/null || fail "No access to the K8s cluster, cannot continue"
 
 # Ensure the namespace exists
-"${KUBECTL}" get namespace "${NAMESPACE}" &>/dev/null || \
-	"${KUBECTL}" create namespace "${NAMESPACE}" || \
+kubectl get namespace "${NAMESPACE}" &>/dev/null || \
+	kubectl create namespace "${NAMESPACE}" || \
 	fail "Failed to create the required namespace [${NAMESPACE}]"
 
 say "👉 Creating Kubernetes secret (${SECRET_NAME}) for [${DOCKER_CONFIG}] in namespace [${NAMESPACE}]..."
 
 # Delete the existing secret, if necessary
-"${KUBECTL}" delete secret \
+kubectl delete secret \
 	--namespace "${NAMESPACE}" \
 	"${SECRET_NAME}" &>/dev/null || true
 
 # Create the replacement secret
-"${KUBECTL}" create secret \
+kubectl create secret \
 	generic \
 	--namespace "${NAMESPACE}" \
 	"${SECRET_NAME}" \
diff --git a/scripts/deploy-environment b/scripts/deploy-environment
--- a/scripts/deploy-environment
+++ b/scripts/deploy-environment
@@ -1,6 +1,6 @@
 #!/bin/bash
-SCRIPT="$(/usr/bin/readlink -f "${BASH_SOURCE:-${0}}")"
-BASEDIR="$(/usr/bin/dirname "${SCRIPT}")"
+SCRIPT="$(readlink -f "${BASH_SOURCE:-${0}}")"
+BASEDIR="$(dirname "${SCRIPT}")"
 
 set -euo pipefail
 
@@ -16,7 +16,7 @@ export DISABLE_DEPLOY
 
 timestamp()
 {
-	/usr/bin/date -Ins -u
+	date -Ins -u
 }
 
 say()
@@ -36,7 +36,7 @@ ok()
 
 err()
 {
-	say "❌ ${@}" 1>&2
+	say "❌ ${@}"
 }
 
 fail()
@@ -73,8 +73,8 @@ execute()
 ensure_namespace_exists()
 {
 	local NAMESPACE="${1}"
-	execute "${KUBECTL}" get namespace "${NAMESPACE}" &>/dev/null && return 0
-	execute "${KUBECTL}" create namespace "${NAMESPACE}" && return 0
+	execute kubectl get namespace "${NAMESPACE}" &>/dev/null && return 0
+	execute kubectl create namespace "${NAMESPACE}" && return 0
 	return 1
 }
 
@@ -86,12 +86,12 @@ sanitize_paths()
 
 	# First, split into parts so we can retain the
 	# declaration order
-	readarray -t PARTS < <(/usr/bin/tr "${SEP}" "\n" <<< "${STR}" | /usr/bin/sed -e '/^\s*$/d')
+	readarray -t PARTS < <(tr "${SEP}" "\n" <<< "${STR}" | sed -e '/^\s*$/d')
 	local LIST=":"
 	for P in "${PARTS[@]}" ; do
 		[ -n "${P}" ] || continue
 		# Skip it if already marked
-		/usr/bin/fgrep -q ":${P}:" <<< "${LIST}" && continue
+		fgrep -q ":${P}:" <<< "${LIST}" && continue
 		LIST+="${P}:"
 		echo "${P}"
 	done
@@ -131,11 +131,8 @@ set -- "${BASE_ARGS[@]}"
 
 [ ${#} -ge 3 ] && [ ${#} -le 4 ] || usage
 
-HELM="$(type -P helm)" || fail "Failed to find helm in the path"
-KUBECTL="$(type -P kubectl)" || fail "Failed to find kubectl in the path"
-
 if [ "${#}" -eq 3 ] ; then
-	NAMESPACE="$("${KUBECTL}" config view --minify -o jsonpath="{..namespace}")"
+	NAMESPACE="$(kubectl config view --minify -o jsonpath="{..namespace}")"
 	[ -n "${NAMESPACE}" ] || NAMESPACE="default"
 else
 	NAMESPACE="${1}"
@@ -163,7 +160,7 @@ is_valid_name "${ENVIRONMENT_NAME}" || fail "Invalid environment name [${ENVIRON
 
 [ -v DEPLOYMENT_DIR ] || DEPLOYMENT_DIR=""
 [ -n "${DEPLOYMENT_DIR}" ] || DEPLOYMENT_DIR="${PWD}"
-DEPLOYMENT_DIR="$(/usr/bin/readlink -f "${DEPLOYMENT_DIR}")" || fail "Failed to canonicalize the path for [${DEPLOYMENT_DIR}]"
+DEPLOYMENT_DIR="$(readlink -f "${DEPLOYMENT_DIR}")" || fail "Failed to canonicalize the path for [${DEPLOYMENT_DIR}]"
 
 say "Deploying from [${DEPLOYMENT_DIR}]..."
 [ -f "${DEPLOYMENT_DIR}/deployment.yaml" ] || fail "This does not seem to be a deployment directory - no deployment.yaml was found!"
@@ -189,7 +186,7 @@ for D in "${COMMON_DIRS[@]}" ; do
 	if [ -d "${COMMON_DIR}" ] ; then
 		while read V ; do
 			VALUES+=(-f "${V}")
-		done < <(/usr/bin/find "${COMMON_DIR}" -type f -iname '*.yaml' | /usr/bin/sort -u)
+		done < <(find "${COMMON_DIR}" -type f -iname '*.yaml' | sort -u)
 	else
 		warn "No common values are being applied from [${COMMON_DIR}] - the directory doesn't exist"
 	fi
@@ -208,7 +205,7 @@ ENV_DIR="${DEPLOYMENT_DIR}/envs/${ENVIRONMENT_NAME}"
 if [ -d "${ENV_DIR}" ] ; then
 	while read V ; do
 		VALUES+=(-f "${V}")
-	done < <(/usr/bin/find "${ENV_DIR}" -type f -iname '*.yaml' | /usr/bin/sort -u)
+	done < <(find "${ENV_DIR}" -type f -iname '*.yaml' | sort -u)
 else
 	warn "No environment folder found at [${DEPLOYMENT_DIR}] for [${ENVIRONMENT_NAME}]"
 fi
@@ -228,7 +225,7 @@ set -- "${HELM_ARGS[@]}"
 # uninstalls
 RC=0
 execute \
-	"${HELM}" install --replace \
+	helm install --replace \
 		"${RELEASE}" "${CHART}" \
 		--namespace "${NAMESPACE}" \
 		--wait \
@@ -243,5 +240,5 @@ else
 	err "The Helm deployment has failed, please review the logs"
 fi
 
-execute "${KUBECTL}" --namespace "${NAMESPACE}" get pods
+execute kubectl --namespace "${NAMESPACE}" get pods
 exit ${RC}
diff --git a/scripts/downscale-environment b/scripts/downscale-environment
--- a/scripts/downscale-environment
+++ b/scripts/downscale-environment
@@ -1,6 +1,6 @@
 #!/bin/bash
-SCRIPT="$(/usr/bin/readlink -f "${BASH_SOURCE:-${0}}")"
-BASEDIR="$(/usr/bin/dirname "${SCRIPT}")"
+SCRIPT="$(readlink -f "${BASH_SOURCE:-${0}}")"
+BASEDIR="$(dirname "${SCRIPT}")"
 
 set -euo pipefail
 
@@ -19,7 +19,7 @@ export DISABLE_DOWNSCALE
 
 timestamp()
 {
-	/usr/bin/date -Ins -u
+	date -Ins -u
 }
 
 say()
@@ -44,7 +44,7 @@ warn()
 
 err()
 {
-	say "❌ ${@}" 1>&2
+	say "❌ ${@}"
 }
 
 fail()
@@ -57,7 +57,7 @@ is_deployed()
 {
 	local NAMESPACE="${1}"
 	local RELEASE="${2}"
-	execute "${HELM}" get --namespace "${NAMESPACE}" all "${RELEASE}" &>/dev/null
+	execute helm get --namespace "${NAMESPACE}" all "${RELEASE}" &>/dev/null
 	return ${?}
 }
 
@@ -180,13 +180,13 @@ list_remaining()
 	local NAMESPACE="${1}"
 	local RELEASE="${2}"
 
-	"${KUBECTL}" \
+	kubectl \
 		get statefulsets.apps \
 		--namespace "${NAMESPACE}" \
 		--selector="app.kubernetes.io/instance=${RELEASE}" \
 		-o json | \
-		"${JQ}" -r '.items[] | select(.status.replicas > 0) | .metadata.name' | \
-		"${SORT}" -u
+		jq -r '.items[] | select(.status.replicas > 0) | .metadata.name' | \
+		sort -u
 }
 
 usage()
@@ -200,13 +200,8 @@ usage()
 DOWNSCALE_TIMEOUT=$(timestr_to_secs "${DOWNSCALE_TIMEOUT}") || fail "Invalid value for DOWNSCALE_TIMEOUT: [${DOWNSCALE_TIMEOUT}]"
 DOWNSCALE_RETRY_WAIT=$(timestr_to_secs "${DOWNSCALE_RETRY_WAIT}") || fail "Invalid value for DOWNSCALE_RETRY_WAIT: [${DOWNSCALE_RETRY_WAIT}]"
 
-HELM="$(type -P helm)" || fail "Failed to find helm in the path"
-JQ="$(type -P jq)" || fail "Failed to find jq in the path"
-KUBECTL="$(type -P kubectl)" || fail "Failed to find kubectl in the path"
-SORT="$(type -P sort)" || fail "Failed to find sort in the path"
-
 if [ ${#} -eq 1 ] ; then
-	NAMESPACE="$("${KUBECTL}" config view --minify -o jsonpath="{..namespace}")"
+	NAMESPACE="$(kubectl config view --minify -o jsonpath="{..namespace}")"
 	[ -n "${NAMESPACE}" ] || NAMESPACE="default"
 else
 	NAMESPACE="${1}"
@@ -224,7 +219,7 @@ is_deployed "${NAMESPACE}" "${RELEASE}" || fail "The release [${RELEASE}] is not
 # NOTE: the timeout is PER ITEM, not total...
 doing "Downscaling the existing StatefulSet instances"
 execute \
-	"${KUBECTL}" scale statefulset \
+	kubectl scale statefulset \
 		--namespace "${NAMESPACE}" \
 		--replicas=0 \
 		--selector="app.kubernetes.io/instance=${RELEASE}" && \
@@ -234,7 +229,7 @@ execute \
 DOWNSCALE_TIMEOUT_STR="$(secs_to_timestr "${DOWNSCALE_TIMEOUT}")"
 DOWNSCALE_RETRY_WAIT_STR="$(secs_to_timestr "${DOWNSCALE_RETRY_WAIT}")"
 say "⌛ Waiting for the downscale to complete (up to ${DOWNSCALE_TIMEOUT_STR} total)..."
-START="$(/usr/bin/date +%s)"
+START="$(date +%s)"
 while true ; do
 
 	# Get the StatefulSets that are still waiting to downscale
@@ -247,7 +242,7 @@ while true ; do
 	warn "There are ${#REMAINING[@]} StatefulSet instances: [ ${REMAINING[@]} ]"
 
 	# There are still some ... have we timed out yet?
-	NOW="$(/usr/bin/date +%s)"
+	NOW="$(date +%s)"
 	(( DIFF = ( NOW - START ) )) || true
 	[ ${DIFF} -lt ${DOWNSCALE_TIMEOUT} ] || fail "Timed out waiting for the StatefulSet instances to scale down to 0"
 
@@ -264,7 +259,7 @@ while true ; do
 	fi
 
 	say "💤 Will wait ${DOWNSCALE_RETRY_WAIT_STR} before the next attempt..."
-	/usr/bin/sleep ${DOWNSCALE_RETRY_WAIT} || fail "Sleep interrupted - cannot continue!"
+	sleep ${DOWNSCALE_RETRY_WAIT} || fail "Sleep interrupted - cannot continue!"
 done
 
 ok "Downscale complete!"
diff --git a/scripts/get-nodejs-version b/scripts/get-nodejs-version
--- a/scripts/get-nodejs-version
+++ b/scripts/get-nodejs-version
@@ -1,7 +1,7 @@
 #!/bin/bash
-SCRIPT="$(/usr/bin/readlink -f "${BASH_SOURCE:-${0}}")"
-BASEDIR="$(/usr/bin/dirname "${SCRIPT}")"
-SCRIPT="$(/usr/bin/basename "${SCRIPT}")"
+SCRIPT="$(readlink -f "${BASH_SOURCE:-${0}}")"
+BASEDIR="$(dirname "${SCRIPT}")"
+SCRIPT="$(basename "${SCRIPT}")"
 
 FUNCTIONS="${BASEDIR}/.functions"
 if ! . "${FUNCTIONS}" ; then
@@ -10,7 +10,26 @@ if ! . "${FUNCTIONS}" ; then
 fi
 unset FUNCTIONS
 
-usage() {
+nodejs_list_libraries()
+{
+	local DIR="${1}"
+	local ANGULAR_JSON="${DIR}/angular.json"
+	if check_file_readable "${ANGULAR_JSON}" ; then
+		ANGULAR_JSON="$(readlink -f "${ANGULAR_JSON}")"
+		jq -r '.projects[] | select (.projectType=="library") | .root' "${ANGULAR_JSON}" | sort -u
+		return ${PIPESTATUS[0]}
+	fi
+
+	find . -type f -name "${PACKAGE_JSON}" -printf "%h\n" | \
+		egrep -v "^[.]$" | \
+		egrep -v '^[.]/dist/' | \
+		sed -e 's;^[.]/;;g' | \
+		sort
+	return ${PIPESTATUS[0]}
+}
+
+usage()
+{
 	echo -e "usage: ${BASH_ARGV0} [directory]"
 	exit 1
 }
@@ -19,26 +38,6 @@ usage() {
 check_help_flag "${@}" && usage
 [ ${#} -gt 1 ] && usage
 [ ${#} -lt 1 ] && set -- "."
-
-# Make sure we have JQ installed
-/usr/bin/which jq &>/dev/null || fail "JQ is not in the path - please correct this and try again"
-
-nodejs_list_libraries() {
-	local DIR="${1}"
-	local ANGULAR_JSON="${DIR}/angular.json"
-	if check_file_readable "${ANGULAR_JSON}" ; then
-		ANGULAR_JSON="$(/usr/bin/readlink -f "${ANGULAR_JSON}")"
-		/usr/bin/jq -r '.projects[] | select (.projectType=="library") | .root' "${ANGULAR_JSON}" | /usr/bin/sort -u
-		return ${PIPESTATUS[0]}
-	fi
-
-	/usr/bin/find . -type f -name "${PACKAGE_JSON}" -printf "%h\n" | \
-		/usr/bin/egrep -v "^[.]$" | \
-		/usr/bin/egrep -v '^[.]/dist/' | \
-		/usr/bin/sed -e 's;^[.]/;;g' | \
-		/usr/bin/sort
-	return ${PIPESTATUS[0]}
-}
 
 DIR="${1}"
 
@@ -52,12 +51,12 @@ cd "${DIR}" || fail "Failed to CD into [${DIR}]"
 
 check_file_readable "${PACKAGE_JSON}" || fail "The file [${PACKAGE_JSON}] must be readable"
 
-VERSION="$(/usr/bin/jq -r ".version" < "${PACKAGE_JSON}")" || fail "Failed to read the JSON in [${PACKAGE_JSON}] in [${DIR}] to get the version number ($?)"
+VERSION="$(jq -r ".version" < "${PACKAGE_JSON}")" || fail "Failed to read the JSON in [${PACKAGE_JSON}] in [${DIR}] to get the version number ($?)"
 echo -e "${PACKAGE_JSON} : ${VERSION}"
 while read LIB ; do
 	JSON="${LIB}/${PACKAGE_JSON}"
 	check_file_readable "${JSON}" || fail "The JSON file [${JSON}] must be readable (${?})"
-	VERSION="$(/usr/bin/jq -r ".version" < "${JSON}")" || fail "Failed to read the JSON in [${JSON}] to get the version number ($?)"
+	VERSION="$(jq -r ".version" < "${JSON}")" || fail "Failed to read the JSON in [${JSON}] to get the version number ($?)"
 	echo -e "${JSON} : ${VERSION}"
-# done < <(/usr/bin/find "${DIR}" -type f -name "${PACKAGE_JSON}" | /usr/bin/sort)
+# done < <(find "${DIR}" -type f -name "${PACKAGE_JSON}" | sort)
 done < <(nodejs_list_libraries "${DIR}")
diff --git a/scripts/get-pom-changelist b/scripts/get-pom-changelist
--- a/scripts/get-pom-changelist
+++ b/scripts/get-pom-changelist
@@ -2,17 +2,17 @@
 
 timestamp()
 {
-	/usr/bin/date -Ins -u
+	date -Ins -u
 }
 
 say()
 {
-	echo -e "${@}"
+	echo -e "$(timestamp): ${@}"
 }
 
 fail()
 {
-	say "❌ ${@}" 1>&2
+	say "❌ ${@}"
 	exit ${EXIT_CODE:-1}
 }
 
@@ -30,11 +30,9 @@ if [ ${#} -eq 1 ] ; then
 	[ -n "${1}" ] || fail "The POM file path may not be the empty string"
 fi
 
-MVN="$(type -P mvn)" || fail "Failed to find the Maven executable in the path, cannot continue!"
-
 [ -e "${POM}" ] || fail "The POM file [${POM}] does not exist"
 [ -f "${POM}" ] || fail "The path [${POM}] is not a regular file"
 [ -r "${POM}" ] || fail "The POM file [${POM}] is not readable"
 
-CHANGELIST="$("${MVN}" -f "${POM}" help:evaluate -Dexpression=changelist -q -DforceStdout 2>&1)" || fail "Failed to compute the changelist using Maven's help:evaluate command: ${CHANGELIST}"
-exec /usr/bin/tr -d '\n' <<< "${CHANGELIST}"
+CHANGELIST="$(mvn -f "${POM}" help:evaluate -Dexpression=changelist -q -DforceStdout 2>&1)" || fail "Failed to compute the changelist using Maven's help:evaluate command: ${CHANGELIST}"
+exec tr -d '\n' <<< "${CHANGELIST}"
diff --git a/scripts/get-pom-version b/scripts/get-pom-version
--- a/scripts/get-pom-version
+++ b/scripts/get-pom-version
@@ -2,17 +2,17 @@
 
 timestamp()
 {
-	/usr/bin/date -Ins -u
+	date -Ins -u
 }
 
 say()
 {
-	echo -e "${@}"
+	echo -e "$(timestamp): ${@}"
 }
 
 fail()
 {
-	say "❌ ${@}" 1>&2
+	say "❌ ${@}"
 	exit ${EXIT_CODE:-1}
 }
 
@@ -30,12 +30,10 @@ if [ ${#} -eq 1 ] ; then
 	[ -n "${1}" ] || fail "The POM file path may not be the empty string"
 fi
 
-XMLSTARLET="$(type -P xmlstarlet)" || fail "Failed to find the xmlstarlet executable in the path, cannot continue!"
-
 [ -e "${POM}" ] || fail "The POM file [${POM}] does not exist"
 [ -f "${POM}" ] || fail "The path [${POM}] is not a regular file"
 [ -r "${POM}" ] || fail "The POM file [${POM}] is not readable"
 
-VERSION="$("${XMLSTARLET}" sel -N "p=http://maven.apache.org/POM/4.0.0" -t -m "/p:project/*" --if 'name()="version"' -v '.' --else -n --break < "${POM}")" || fail "Failed to parse the /project/version node from the POM file [${POM}]"
+VERSION="$(xmlstarlet sel -N "p=http://maven.apache.org/POM/4.0.0" -t -m "/p:project/*" --if 'name()="version"' -v '.' --else -n --break < "${POM}")" || fail "Failed to parse the /project/version node from the POM file [${POM}]"
 
-exec /usr/bin/tr -d '\n' <<< "${VERSION}"
+exec tr -d '\n' <<< "${VERSION}"
diff --git a/scripts/login-aws b/scripts/login-aws
--- a/scripts/login-aws
+++ b/scripts/login-aws
@@ -1,25 +1,25 @@
 #!/bin/bash
-SCRIPT="$(/usr/bin/readlink -f "${BASH_SOURCE:-${0}}")"
-BASEDIR="$(/usr/bin/dirname "${SCRIPT}")"
-SCRIPT="$(/usr/bin/basename "${SCRIPT}")"
+SCRIPT="$(readlink -f "${BASH_SOURCE:-${0}}")"
+BASEDIR="$(dirname "${SCRIPT}")"
+SCRIPT="$(basename "${SCRIPT}")"
 
 set -euo pipefail
 
 timestamp()
 {
-	/usr/bin/date -Ins -u
+	date -Ins -u
 }
 
-say() {
+say()
+{
 	echo -e "$(timestamp): ${@}"
 }
 
-fail() {
-	say "❌ ${@}" 1>&2
+fail()
+{
+	say "❌ ${@}"
 	exit ${EXIT_CODE:-1}
 }
-
-AWS="$(type -P aws)" || fail "The 'aws' executable is not in the path - cannot continue"
 
 [ -v AWS_USERNAME ] || AWS_USERNAME="AWS"
 
@@ -31,14 +31,14 @@ export AWS_REGION
 say "👉 Using region ${AWS_REGION}"
 say "👉 Logging in with credentials from the environment"
 
-AWS_ACCOUNT_ID=$("${AWS}" sts get-caller-identity --query Account --output text 2>&1) || fail "Failed to get the account ID (rc = ${?}): ${AWS_ACCOUNT_ID}"
+AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text 2>&1) || fail "Failed to get the account ID (rc = ${?}): ${AWS_ACCOUNT_ID}"
 [[ "${AWS_ACCOUNT_ID}" =~ ^[0-9]+$ ]] || fail "The account ID [${AWS_ACCOUNT_ID}] is invalid - must be a number!"
 say "\t✅ Account ID identified!"
 
 HOST="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
 
 say "👉 Fetching the AWS login password for Docker (account ID ${AWS_ACCOUNT_ID})..."
-PASS="$("${AWS}" ecr get-login-password --region "${AWS_REGION}" 2>&1)" || fail "Failed to fetch the AWS login password for account ${AWS_ACCOUNT_ID} (rc = ${?}): ${PASS}"
+PASS="$(aws ecr get-login-password --region "${AWS_REGION}" 2>&1)" || fail "Failed to fetch the AWS login password for account ${AWS_ACCOUNT_ID} (rc = ${?}): ${PASS}"
 say "\t✅ Docker password retrieved!"
 
 # Launch the docker login
diff --git a/scripts/login-docker b/scripts/login-docker
--- a/scripts/login-docker
+++ b/scripts/login-docker
@@ -1,21 +1,23 @@
 #!/bin/bash
-SCRIPT="$(/usr/bin/readlink -f "${BASH_SOURCE:-${0}}")"
-BASEDIR="$(/usr/bin/dirname "${SCRIPT}")"
-SCRIPT="$(/usr/bin/basename "${SCRIPT}")"
+SCRIPT="$(readlink -f "${BASH_SOURCE:-${0}}")"
+BASEDIR="$(dirname "${SCRIPT}")"
+SCRIPT="$(basename "${SCRIPT}")"
 
 set -euo pipefail
 
 timestamp()
 {
-	/usr/bin/date -Ins -u
+	date -Ins -u
 }
 
-say() {
+say()
+{
 	echo -e "$(timestamp): ${@}"
 }
 
-fail() {
-	say "❌ ${@}" 1>&2
+fail()
+{
+	say "❌ ${@}"
 	exit ${EXIT_CODE:-1}
 }
 
@@ -24,8 +26,6 @@ usage()
 	echo -e "usage: ${BASH_ARGV0:-${BASH_SOURCE:-${0}}} [hostname]" 1>&2
 	exit 1
 }
-
-DOCKER="$(type -P docker)" || fail "The 'docker' executable is not in the path - cannot continue"
 
 [ ${#} -le 1 ] || usage
 
@@ -46,9 +46,9 @@ if [ -v DOCKER_PASSWORD ] ; then
 	say "👉 Logging in with Docker credentials from the environment"
 else
 	say "👉 Logging in with Docker credentials from STDIN..."
-	DOCKER_PASSWORD="$(/usr/bin/cat)"
+	DOCKER_PASSWORD="$(cat)"
 fi
 
-"${DOCKER}" login --username "${DOCKER_USERNAME}" --password-stdin "${HOST[@]}" <<< "${DOCKER_PASSWORD}" || fail "Docker login failed (rc = ${?})"
+docker login --username "${DOCKER_USERNAME}" --password-stdin "${HOST[@]}" <<< "${DOCKER_PASSWORD}" || fail "Docker login failed (rc = ${?})"
 say "\t✅ Docker login succeeded!"
 exit 0
diff --git a/scripts/rancher-add-ns-to-project b/scripts/rancher-add-ns-to-project
--- a/scripts/rancher-add-ns-to-project
+++ b/scripts/rancher-add-ns-to-project
@@ -1,12 +1,12 @@
 #!/bin/bash
-SCRIPT="$(/usr/bin/readlink -f "${BASH_SOURCE:-${0}}")"
-BASEDIR="$(/usr/bin/dirname "${SCRIPT}")"
+SCRIPT="$(readlink -f "${BASH_SOURCE:-${0}}")"
+BASEDIR="$(dirname "${SCRIPT}")"
 
 set -euo pipefail
 
 timestamp()
 {
-	/usr/bin/date -Ins -u
+	date -Ins -u
 }
 
 say()
@@ -16,7 +16,7 @@ say()
 
 fail()
 {
-	say "❌ ${@}" 1>&2
+	say "❌ ${@}"
 	exit ${EXIT_CODE:-1}
 }
 
@@ -33,7 +33,7 @@ auth_params()
 		PASS="${2}"
 	fi
 
-	"${CAT}" <<-EOF
+	cat <<-EOF
 	user "${USER}:${PASS}"
 	EOF
 }
@@ -72,11 +72,6 @@ CLUSTER_NAME="${2}"
 PROJECT_NAME="${3}"
 [ -n "${PROJECT_NAME}" ] || fail "Must provide a non-empty project name"
 
-KUBECTL="$(type -P kubectl)" || fail "Could not find 'kubectl' in the path"
-CURL="$(type -P curl)" || fail "Could not find 'curl' in the path"
-JQ="$(type -P jq)" || fail "Could not find 'jq' in the path"
-CAT="$(type -P cat)" || fail "Could not find 'cat' in the path"
-
 PROJECT_INFO="$("${BASEDIR}/rancher-get-project-id" "${CLUSTER_NAME}" "${PROJECT_NAME}")" || exit 1
 
 [[ "${PROJECT_INFO}" =~ ^([^/]+)/([^/]+)$ ]] || fail "Invalid project information: [${PROJECT_INFO}]"
@@ -86,7 +81,7 @@ PROJECT_ID="${BASH_REMATCH[2]}"
 
 RANCHER_API_ENDPOINT+="/k8s/clusters/${CLUSTER_ID}/v1/namespaces"
 
-PATCH_JSON="$("${CAT}" <<-EOF
+PATCH_JSON="$(cat <<-EOF
 {
 	"metadata": {
 		"annotations": {
@@ -101,9 +96,9 @@ EOF
 )"
 
 say "👉 Patching the namespace ${NAMESPACE} for the project ${PROJECT_NAME} in the cluster ${CLUSTER_NAME}..."
-"${KUBECTL}" patch namespace "${NAMESPACE}" -p "${PATCH_JSON}" || fail "Failed to patch the namespace ${NAMESPACE}:\n${PATCH_JSON}"
+kubectl patch namespace "${NAMESPACE}" -p "${PATCH_JSON}" || fail "Failed to patch the namespace ${NAMESPACE}:\n${PATCH_JSON}"
 
-API_JSON="$("${CAT}" <<-EOF
+API_JSON="$(cat <<-EOF
 {
 	"metadata": {
 		"annotations": {
@@ -118,14 +113,14 @@ EOF
 
 say "👉 Adding the namespace ${NAMESPACE} into the project ${PROJECT_NAME} in the cluster ${CLUSTER_NAME}..."
 OUT="$(
-	"${CURL}" -sSL \
+	curl -sSL \
 	--config <(auth_params "${RANCHER_TOKEN}") \
 	--header "Content-Type: application/json" \
 	--data "${API_JSON}" \
 	"${RANCHER_API_ENDPOINT}" 2>&1
 )"
 
-read STATUS TYPE CODE < <("${JQ}" -r '((.status // "-") | tostring) + " " + (.type // "-") + " " + (.code // "-")' <<< "${OUT}")
+read STATUS TYPE CODE < <(jq -r '((.status // "-") | tostring) + " " + (.type // "-") + " " + (.code // "-")' <<< "${OUT}")
 
 RESULT="added"
 case "${STATUS}" in
diff --git a/scripts/rancher-get-cluster-id b/scripts/rancher-get-cluster-id
--- a/scripts/rancher-get-cluster-id
+++ b/scripts/rancher-get-cluster-id
@@ -1,12 +1,12 @@
 #!/bin/bash
-SCRIPT="$(/usr/bin/readlink -f "${BASH_SOURCE:-${0}}")"
-BASEDIR="$(/usr/bin/dirname "${SCRIPT}")"
+SCRIPT="$(readlink -f "${BASH_SOURCE:-${0}}")"
+BASEDIR="$(dirname "${SCRIPT}")"
 
 set -euo pipefail
 
 timestamp()
 {
-	/usr/bin/date -Ins -u
+	date -Ins -u
 }
 
 say()
@@ -14,9 +14,14 @@ say()
 	echo -e "$(timestamp): ${@}"
 }
 
+err()
+{
+	say "❌ ${@}"
+}
+
 fail()
 {
-	say "❌ ${@}" 1>&2
+	err "${@}"
 	exit ${EXIT_CODE:-1}
 }
 
@@ -33,7 +38,7 @@ auth_params()
 		PASS="${2}"
 	fi
 
-	"${CAT}" <<-EOF
+	cat <<-EOF
 	user "${USER}:${PASS}"
 	EOF
 }
@@ -66,11 +71,7 @@ RANCHER_API_ENDPOINT="${BASH_REMATCH[0]}/v3/clusters"
 CLUSTER_NAME="${1}"
 [ -n "${CLUSTER_NAME}" ] || fail "Must provide a non-empty cluster name"
 
-CURL="$(type -P curl)" || fail "Could not find 'curl' in the path"
-JQ="$(type -P jq)" || fail "Could not find 'jq' in the path"
-CAT="$(type -P cat)" || fail "Could not find 'cat' in the path"
-
-CLUSTER_ID="$("${CURL}" -fsSL --config <(auth_params "${RANCHER_TOKEN}") "${RANCHER_API_ENDPOINT}" | "${JQ}" -r ".data[] | select(.name == \"${CLUSTER_NAME}\") | .id")" || fail "Failed to query the cluster ID for [${CLUSTER_NAME}] (rc=${?})"
+CLUSTER_ID="$(curl -fsSL --config <(auth_params "${RANCHER_TOKEN}") "${RANCHER_API_ENDPOINT}" | jq -r ".data[] | select(.name == \"${CLUSTER_NAME}\") | .id")" || fail "Failed to query the cluster ID for [${CLUSTER_NAME}] (rc=${?})"
 [ -n "${CLUSTER_ID}" ] || fail "No cluster ID was returned for [${CLUSTER_NAME}]"
 echo "${CLUSTER_ID}"
 exit 0
diff --git a/scripts/rancher-get-clusters b/scripts/rancher-get-clusters
--- a/scripts/rancher-get-clusters
+++ b/scripts/rancher-get-clusters
@@ -1,12 +1,12 @@
 #!/bin/bash
-SCRIPT="$(/usr/bin/readlink -f "${BASH_SOURCE:-${0}}")"
-BASEDIR="$(/usr/bin/dirname "${SCRIPT}")"
+SCRIPT="$(readlink -f "${BASH_SOURCE:-${0}}")"
+BASEDIR="$(dirname "${SCRIPT}")"
 
 set -euo pipefail
 
 timestamp()
 {
-	/usr/bin/date -Ins -u
+	date -Ins -u
 }
 
 say()
@@ -14,9 +14,14 @@ say()
 	echo -e "$(timestamp): ${@}"
 }
 
+err()
+{
+	say "❌ ${@}"
+}
+
 fail()
 {
-	say "❌ ${@}" 1>&2
+	err "${@}"
 	exit ${EXIT_CODE:-1}
 }
 
@@ -33,7 +38,7 @@ auth_params()
 		PASS="${2}"
 	fi
 
-	"${CAT}" <<-EOF
+	cat <<-EOF
 	user "${USER}:${PASS}"
 	EOF
 }
@@ -55,11 +60,6 @@ auth_params()
 [[ "${RANCHER_API_URL}" =~ ^(.*)/*$ ]] || fail "Invalid Rancher API URL [${RANCHER_API_URL}]"
 RANCHER_API_ENDPOINT="${BASH_REMATCH[0]}/v3/clusters"
 
-CURL="$(type -P curl)" || fail "Could not find 'curl' in the path"
-SORT="$(type -P sort)" || fail "Could not find 'sort' in the path"
-JQ="$(type -P jq)" || fail "Could not find 'jq' in the path"
-CAT="$(type -P cat)" || fail "Could not find 'cat' in the path"
-
-LIST="$("${CURL}" -fsSL --config <(auth_params "${RANCHER_TOKEN}") "${RANCHER_API_ENDPOINT}" | "${JQ}" -r ".data[] | .id + \" \" + .name")" || fail "Failed to query the cluster list (rc=${?})"
-echo "${LIST}" | "${SORT}" -k 2
+LIST="$(curl -fsSL --config <(auth_params "${RANCHER_TOKEN}") "${RANCHER_API_ENDPOINT}" | jq -r ".data[] | .id + \" \" + .name")" || fail "Failed to query the cluster list (rc=${?})"
+echo "${LIST}" | sort -k 2
 exit 0
diff --git a/scripts/rancher-get-kubeconfig b/scripts/rancher-get-kubeconfig
--- a/scripts/rancher-get-kubeconfig
+++ b/scripts/rancher-get-kubeconfig
@@ -1,12 +1,12 @@
 #!/bin/bash
-SCRIPT="$(/usr/bin/readlink -f "${BASH_SOURCE:-${0}}")"
-BASEDIR="$(/usr/bin/dirname "${SCRIPT}")"
+SCRIPT="$(readlink -f "${BASH_SOURCE:-${0}}")"
+BASEDIR="$(dirname "${SCRIPT}")"
 
 set -euo pipefail
 
 timestamp()
 {
-	/usr/bin/date -Ins -u
+	date -Ins -u
 }
 
 say()
@@ -14,9 +14,14 @@ say()
 	echo -e "$(timestamp): ${@}"
 }
 
+err()
+{
+	say "❌ ${@}"
+}
+
 fail()
 {
-	say "❌ ${@}" 1>&2
+	err "${@}"
 	exit ${EXIT_CODE:-1}
 }
 
@@ -33,7 +38,7 @@ auth_params()
 		PASS="${2}"
 	fi
 
-	"${CAT}" <<-EOF
+	cat <<-EOF
 	user "${USER}:${PASS}"
 	EOF
 }
@@ -75,12 +80,8 @@ if [ ${#} -gt 1 ] ; then
 	[ -n "${TARGET_FILE}" ] || fail "Must provide a non-empty target filename"
 fi
 
-CURL="$(type -P curl)" || fail "Could not find 'curl' in the path"
-JQ="$(type -P jq)" || fail "Could not find 'jq' in the path"
-CAT="$(type -P cat)" || fail "Could not find 'cat' in the path"
-
 CLUSTER_ID="$("${BASEDIR}/rancher-get-cluster-id" "${CLUSTER_NAME}")" || exit 1
-CLUSTER_CONFIG="$("${CURL}" -fsSL -X POST --config <(auth_params "${RANCHER_TOKEN}") "${RANCHER_API_ENDPOINT}/${CLUSTER_ID}?action=generateKubeconfig" | jq -r ".config")" || fail "Failed to retrieve the cluster configuration for cluster [${CLUSTER_NAME}](${CLUSTER_ID})"
+CLUSTER_CONFIG="$(curl -fsSL -X POST --config <(auth_params "${RANCHER_TOKEN}") "${RANCHER_API_ENDPOINT}/${CLUSTER_ID}?action=generateKubeconfig" | jq -r ".config")" || fail "Failed to retrieve the cluster configuration for cluster [${CLUSTER_NAME}](${CLUSTER_ID})"
 
 #
 # Write to STDOUT
diff --git a/scripts/rancher-get-project-id b/scripts/rancher-get-project-id
--- a/scripts/rancher-get-project-id
+++ b/scripts/rancher-get-project-id
@@ -1,12 +1,12 @@
 #!/bin/bash
-SCRIPT="$(/usr/bin/readlink -f "${BASH_SOURCE:-${0}}")"
-BASEDIR="$(/usr/bin/dirname "${SCRIPT}")"
+SCRIPT="$(readlink -f "${BASH_SOURCE:-${0}}")"
+BASEDIR="$(dirname "${SCRIPT}")"
 
 set -euo pipefail
 
 timestamp()
 {
-	/usr/bin/date -Ins -u
+	date -Ins -u
 }
 
 say()
@@ -14,9 +14,14 @@ say()
 	echo -e "$(timestamp): ${@}"
 }
 
+err()
+{
+	say "❌ ${@}"
+}
+
 fail()
 {
-	say "❌ ${@}" 1>&2
+	err "${@}"
 	exit ${EXIT_CODE:-1}
 }
 
@@ -33,7 +38,7 @@ auth_params()
 		PASS="${2}"
 	fi
 
-	"${CAT}" <<-EOF
+	cat <<-EOF
 	user "${USER}:${PASS}"
 	EOF
 }
@@ -69,12 +74,8 @@ CLUSTER_NAME="${1}"
 PROJECT_NAME="${2}"
 [ -n "${PROJECT_NAME}" ] || fail "Must provide a non-empty project name"
 
-CURL="$(type -P curl)" || fail "Could not find 'curl' in the path"
-JQ="$(type -P jq)" || fail "Could not find 'jq' in the path"
-CAT="$(type -P cat)" || fail "Could not find 'cat' in the path"
-
 CLUSTER_ID="$("${BASEDIR}/rancher-get-cluster-id" "${CLUSTER_NAME}")" || exit 1
 RANCHER_API_ENDPOINT+="/${CLUSTER_ID}"
-PROJECT_ID="$("${CURL}" -fsSL --config <(auth_params "${RANCHER_TOKEN}") "${RANCHER_API_ENDPOINT}" | "${JQ}" -r ".data[] | select(.spec.displayName == \"${PROJECT_NAME}\") | .id")" || fail "Could not find the project named [${PROJECT_NAME}] in the ${CLUSTER_NAME} cluster"
+PROJECT_ID="$(curl -fsSL --config <(auth_params "${RANCHER_TOKEN}") "${RANCHER_API_ENDPOINT}" | jq -r ".data[] | select(.spec.displayName == \"${PROJECT_NAME}\") | .id")" || fail "Could not find the project named [${PROJECT_NAME}] in the ${CLUSTER_NAME} cluster"
 echo "${PROJECT_ID}"
 exit 0
diff --git a/scripts/rancher-get-projects b/scripts/rancher-get-projects
--- a/scripts/rancher-get-projects
+++ b/scripts/rancher-get-projects
@@ -1,12 +1,12 @@
 #!/bin/bash
-SCRIPT="$(/usr/bin/readlink -f "${BASH_SOURCE:-${0}}")"
-BASEDIR="$(/usr/bin/dirname "${SCRIPT}")"
+SCRIPT="$(readlink -f "${BASH_SOURCE:-${0}}")"
+BASEDIR="$(dirname "${SCRIPT}")"
 
 set -euo pipefail
 
 timestamp()
 {
-	/usr/bin/date -Ins -u
+	date -Ins -u
 }
 
 say()
@@ -14,9 +14,14 @@ say()
 	echo -e "$(timestamp): ${@}"
 }
 
+err()
+{
+	say "❌ ${@}"
+}
+
 fail()
 {
-	say "❌ ${@}" 1>&2
+	err "${@}"
 	exit ${EXIT_CODE:-1}
 }
 
@@ -33,7 +38,7 @@ auth_params()
 		PASS="${2}"
 	fi
 
-	"${CAT}" <<-EOF
+	cat <<-EOF
 	user "${USER}:${PASS}"
 	EOF
 }
@@ -66,13 +71,8 @@ RANCHER_API_ENDPOINT="${BASH_REMATCH[0]}/v1/management.cattle.io.projects"
 CLUSTER_NAME="${1}"
 [ -n "${CLUSTER_NAME}" ] || fail "Must provide a non-empty cluster name"
 
-CURL="$(type -P curl)" || fail "Could not find 'curl' in the path"
-JQ="$(type -P jq)" || fail "Could not find 'jq' in the path"
-CAT="$(type -P cat)" || fail "Could not find 'cat' in the path"
-SORT="$(type -P sort)" || fail "Could not find 'sort' in the path"
-
 CLUSTER_ID="$("${BASEDIR}/rancher-get-cluster-id" "${CLUSTER_NAME}")" || exit 1
 RANCHER_API_ENDPOINT+="/${CLUSTER_ID}"
-LIST="$("${CURL}" -fsSL --config <(auth_params "${RANCHER_TOKEN}") "${RANCHER_API_ENDPOINT}" | "${JQ}" -r ".data[] | .id + \" \" + .spec.displayName")" || fail "Could not find the project listing in cluster ${CLUSTER_NAME}"
-echo "${LIST}" | "${SORT}" -k 2
+LIST="$(curl -fsSL --config <(auth_params "${RANCHER_TOKEN}") "${RANCHER_API_ENDPOINT}" | jq -r ".data[] | .id + \" \" + .spec.displayName")" || fail "Could not find the project listing in cluster ${CLUSTER_NAME}"
+echo "${LIST}" | sort -k 2
 exit 0
diff --git a/scripts/set-project-version b/scripts/set-project-version
--- a/scripts/set-project-version
+++ b/scripts/set-project-version
@@ -1,7 +1,7 @@
 #!/bin/bash
-SCRIPT="$(/usr/bin/readlink -f "${BASH_SOURCE:-${0}}")"
-BASEDIR="$(/usr/bin/dirname "${SCRIPT}")"
-SCRIPT="$(/usr/bin/basename "${SCRIPT}")"
+SCRIPT="$(readlink -f "${BASH_SOURCE:-${0}}")"
+BASEDIR="$(dirname "${SCRIPT}")"
+SCRIPT="$(basename "${SCRIPT}")"
 
 FUNCTIONS="${BASEDIR}/.functions"
 if ! . "${FUNCTIONS}" ; then
@@ -10,36 +10,19 @@ if ! . "${FUNCTIONS}" ; then
 fi
 unset FUNCTIONS
 
-usage() {
+usage()
+{
 	echo -e "usage: ${BASH_ARGV0} version [directory] [-h|-?|--help]"
 	exit 1
 }
 
-cleanup() {
-	[ -n "${BUFFER}" ] && :> "${BUFFER}" && /usr/bin/rm -rf "${BUFFER}" &>/dev/null
+cleanup()
+{
+	[ -n "${BUFFER}" ] && :> "${BUFFER}" && rm -rf "${BUFFER}" &>/dev/null
 }
 
-trap cleanup EXIT
-
-check_help_flag "${@}" && usage
-[ ${#} -gt 2 ] && usage
-[ ${#} -lt 1 ] && usage
-
-# If no directory list is given, assume the first directory will be the current one
-[ ${#} -lt 2 ] && set -- "${1}" "."
-
-VERSION="${1}"
-[ -z "${VERSION}" ] && fail "The version may not be the empty string"
-[[ "${VERSION}" =~ [[:space:]] ]] && fail "The version may not contain spaces"
-
-DIR="${2}"
-check_dir_writable "${DIR}" || fail "Can't write to the directory [${DIR}]"
-
-# Make sure we have JQ installed
-/usr/bin/which jq &>/dev/null || fail "JQ is not in the path - please correct this and try again"
-/usr/bin/which xmlstarlet &>/dev/null || fail "xmlstarlet is not in the path - please correct this and try again"
-
-maven_set_version() {
+maven_set_version()
+{
 	local VERSION="${1}"
 	local DIR="${2}"
 
@@ -47,12 +30,12 @@ maven_set_version() {
 	check_file "${POM_XML}" || return 0
 
 	check_dir_readwrite "${DIR}" || fail "The directory [${DIR}] must be readable and writable"
-	DIR="$(/usr/bin/readlink -f "${DIR}")"
+	DIR="$(readlink -f "${DIR}")"
 
 	check_file_readwrite "${POM_XML}" || fail "The file [${POM_XML}] must be readable and writable"
 
 	say "Setting the POM version number to [${VERSION}] in all relevant files within [${DIR}], recursively ..."
-	local V="$(/usr/bin/xmlstarlet sel -N 'p=http://maven.apache.org/POM/4.0.0' -t -v '/p:project/p:version' < "${POM_XML}")"
+	local V="$(xmlstarlet sel -N 'p=http://maven.apache.org/POM/4.0.0' -t -v '/p:project/p:version' < "${POM_XML}")"
 	[ -n "${V}" ] || fail "The POM file at [${POM_XML}] is invalid - the version string is empty"
 	local GOAL="set"
 	local ARGS=()
@@ -67,40 +50,43 @@ maven_set_version() {
 	return 0
 }
 
-nodejs_apply_version() {
+nodejs_apply_version()
+{
 	local VERSION="${1}"
 	local JSON="${2}"
 
 	check_file_readwrite "${JSON}" || fail "The JSON file [${JSON}] must be both readable and writable (${?})"
 	say "Processing [${JSON}]"
-	/usr/bin/jq --indent 4 --arg VERSION "${VERSION}" '.version = $VERSION' < "${JSON}" > "${BUFFER}" || fail "Failed to render the JSON for [${JSON}] using the new version number [${VERSION}]"
+	jq --indent 4 --arg VERSION "${VERSION}" '.version = $VERSION' < "${JSON}" > "${BUFFER}" || fail "Failed to render the JSON for [${JSON}] using the new version number [${VERSION}]"
 
 	local BAK="${JSON}.bak"
-	/usr/bin/cat "${JSON}" > "${BAK}" || fail "Failed to create a backup file for [${JSON}]"
-	if /usr/bin/cat "${BUFFER}" > "${JSON}" ; then
-		/usr/bin/rm -f "${BAK}" &>/dev/null
+	cat "${JSON}" > "${BAK}" || fail "Failed to create a backup file for [${JSON}]"
+	if cat "${BUFFER}" > "${JSON}" ; then
+		rm -f "${BAK}" &>/dev/null
 		return 0
 	fi
 
-	/usr/bin/cat "${BAK}" > "${JSON}"
-	/usr/bin/rm -f "${BAK}" &>/dev/null
+	cat "${BAK}" > "${JSON}"
+	rm -f "${BAK}" &>/dev/null
 	err "Failed to write the new JSON with version [${VERSION}] into [${JSON}]"
 	return 1
 }
 
-nodejs_list_libraries() {
+nodejs_list_libraries()
+{
 	local DIR="${1}"
 	local ANGULAR_JSON="${DIR}/angular.json"
 	if ! check_file_readable "${ANGULAR_JSON}" ; then
 		err "The file [${ANGULAR_JSON}] must be readable"
 		return 1
 	fi
-	ANGULAR_JSON="$(/usr/bin/readlink -f "${ANGULAR_JSON}")"
-	/usr/bin/jq -r '.projects[] | select (.projectType=="library") | .root' "${ANGULAR_JSON}" | /usr/bin/sort -u
+	ANGULAR_JSON="$(readlink -f "${ANGULAR_JSON}")"
+	jq -r '.projects[] | select (.projectType=="library") | .root' "${ANGULAR_JSON}" | sort -u
 	return ${PIPESTATUS[0]}
 }
 
-nodejs_set_version() {
+nodejs_set_version()
+{
 	local VERSION="${1}"
 	local DIR="${2}"
 	local PACKAGE_JSON="package.json"
@@ -110,7 +96,7 @@ nodejs_set_version() {
 
 	say "Setting NodeJS version data"
 	check_dir_readwrite "${DIR}" || fail "The directory [${DIR}] must be readable and writable"
-	DIR="$(/usr/bin/readlink -f "${DIR}")"
+	DIR="$(readlink -f "${DIR}")"
 
 	ROOT_PACKAGE_JSON="${DIR}/${PACKAGE_JSON}"
 	check_file_readwrite "${ROOT_PACKAGE_JSON}" || fail "The file [${ROOT_PACKAGE_JSON}] must be readable and writable"
@@ -131,7 +117,23 @@ nodejs_set_version() {
 	return 0
 }
 
-BUFFER="$(/usr/bin/mktemp --suffix=.json package.XXXXXXXX)"
+trap cleanup EXIT
+
+check_help_flag "${@}" && usage
+[ ${#} -gt 2 ] && usage
+[ ${#} -lt 1 ] && usage
+
+# If no directory list is given, assume the first directory will be the current one
+[ ${#} -lt 2 ] && set -- "${1}" "."
+
+VERSION="${1}"
+[ -z "${VERSION}" ] && fail "The version may not be the empty string"
+[[ "${VERSION}" =~ [[:space:]] ]] && fail "The version may not contain spaces"
+
+DIR="${2}"
+check_dir_writable "${DIR}" || fail "Can't write to the directory [${DIR}]"
+
+BUFFER="$(mktemp --suffix=.json package.XXXXXXXX)"
 cd "${DIR}" || fail "Failed to CD into [${DIR}]"
 maven_set_version "${VERSION}" "${DIR}" || fail "Failed to set the POM version for [${DIR}]"
 nodejs_set_version "${VERSION}" "${DIR}" || fail "Failed to set the NodeJS version for [${DIR}]"
diff --git a/scripts/veracode-fetch-scan b/scripts/veracode-fetch-scan
--- a/scripts/veracode-fetch-scan
+++ b/scripts/veracode-fetch-scan
@@ -1,29 +1,39 @@
 #!/bin/bash
-SCRIPT="$(/usr/bin/readlink -f "${BASH_SOURCE:-${0}}")"
-BASEDIR="$(/usr/bin/dirname "${SCRIPT}")"
-SCRIPT="$(/usr/bin/basename "${SCRIPT}")"
+SCRIPT="$(readlink -f "${BASH_SOURCE:-${0}}")"
+BASEDIR="$(dirname "${SCRIPT}")"
+SCRIPT="$(basename "${SCRIPT}")"
 
 set -euo pipefail
 
-timestamp() {
-	/usr/bin/date -Ins -u
+timestamp()
+{
+	date -Ins -u
 }
 
-say() {
+say()
+{
 	echo -e "$(timestamp): ${@}"
 }
 
-fail() {
-	say "❌ ${@}" 1>&2
+err()
+{
+	say "❌ ${@}"
+}
+
+fail()
+{
+	err "${@}"
 	exit ${EXIT_CODE:-1}
 }
 
-usage() {
+usage()
+{
 	echo -e "usage: ${BASH_ARGV0:-${BASH_SOURCE:-${0}}} appId [targetPath]" 1>&2
 	exit 1
 }
 
-cleanup() {
+cleanup()
+{
 	if [ -v WORKDIR ] ; then
 		[ -d "${WORKDIR}" ] && rm -rf "${WORKDIR}" || true
 	fi
@@ -42,15 +52,10 @@ TARGET_PATH=""
 if [ ${#} -eq 2 ] ; then
 	TARGET_PATH="${2}"
 else
-	TARGET_PATH="$(/usr/bin/mktemp -d)"
+	TARGET_PATH="$(mktemp -d)"
 fi
 [ -n "${TARGET_PATH}" ] || fail "The target path may not be an empty string"
 [ -d "${TARGET_PATH}" ] || mkdir -p "${TARGET_PATH}" || fail "Failed to ensure that the target path [${TARGET_PATH}] existed"
-
-VERACODE="$(type -P veracode 2>/dev/null)" || fail "The veracode executable could not be found in the PATH"
-XMLSTARLET="$(type -P xmlstarlet 2>/dev/null)" || fail "The xmlstarlet executable could not be found in the PATH"
-STAT="$(type -P stat 2>/dev/null)" || fail "The stat executable could not be found in the PATH"
-SHA256SUM="$(type -P sha256sum 2>/dev/null)" || fail "The sha256sum executable could not be found in the PATH"
 
 [ -v VERACODE_API_KEY_ID ] || fail "The VERACODE_API_KEY_ID variable is not set, cannot continue"
 [ -n "${VERACODE_API_KEY_ID}" ] || fail "The VERACODE_API_KEY_ID variable has an empty value, cannot continue"
@@ -73,11 +78,11 @@ BUILD_ID=()
 # Compute the application ID based on the name
 APP_ID="$("${BASEDIR}/veracode-get-app-id" "${APP_NAME}")" || fail "Failed to get the application ID for [${APP_NAME}]"
 
-PROBE_START="$(/usr/bin/date +%s)"
+PROBE_START="$(date +%s)"
 while true ; do
 
 	# First things first!! Check the timeout!
-	PROBE_NOW="$(/usr/bin/date +%s)"
+	PROBE_NOW="$(date +%s)"
 	[ $(( PROBE_NOW - PROBE_START )) -lt $(( VERACODE_TIMEOUT * 60 )) ] || fail "Timed out waiting for the scan to complete"
 
 	# No timeout? No problem!!
@@ -88,16 +93,16 @@ while true ; do
 	fi
 
 	BUILDINFO="${TARGET_PATH}/${APP_NAME}.build-info.xml"
-	"${VERACODE}" -action GetBuildInfo -appid "${APP_ID}" "${BUILD_ID[@]}" -format xml > "${BUILDINFO}" || fail "Failed to fetch the build information!"
+	veracode -action GetBuildInfo -appid "${APP_ID}" "${BUILD_ID[@]}" -format xml > "${BUILDINFO}" || fail "Failed to fetch the build information!"
 	say "\t✅ Build information retrieved!"
 
 	if [ -z "${VERACODE_BUILD_ID}" ] ; then
-		VERACODE_BUILD_ID="$("${XMLSTARLET}" sel -N "bi=https://analysiscenter.veracode.com/schema/4.0/buildinfo" -t -v "/bi:buildinfo/bi:build/@build_id" < "${BUILDINFO}")"
+		VERACODE_BUILD_ID="$(xmlstarlet sel -N "bi=https://analysiscenter.veracode.com/schema/4.0/buildinfo" -t -v "/bi:buildinfo/bi:build/@build_id" < "${BUILDINFO}")"
 		say "\t⚠️ the BUILD_ID is [${VERACODE_BUILD_ID}]"
 		BUILD_ID=(-buildid "${VERACODE_BUILD_ID}")
 	fi
 
-	STATUS="$("${XMLSTARLET}" sel -N "bi=https://analysiscenter.veracode.com/schema/4.0/buildinfo" -t -v "/bi:buildinfo/bi:build/bi:analysis_unit/@status" < "${BUILDINFO}")"
+	STATUS="$(xmlstarlet sel -N "bi=https://analysiscenter.veracode.com/schema/4.0/buildinfo" -t -v "/bi:buildinfo/bi:build/bi:analysis_unit/@status" < "${BUILDINFO}")"
 	say "\t⚠️ the build status is [${STATUS}]"
 	case "${STATUS^^}" in
 
@@ -107,7 +112,7 @@ while true ; do
 		# These are "waitable" statuses
 		"VENDOR CONFIRMATION" | "VENDOR REVIEWING" | "PRE-SCAN SUBMITTED" | "PRE-SCAN SUCCESS" | "SCAN IN PROCESS" )
 			say "\t💤 The scan is still running, sleeping for ${VERACODE_PROBE_SECONDS} seconds before probing again"
-			/usr/bin/sleep "${VERACODE_PROBE_SECONDS}" || fail "Sleep interrupted, cannot continue"
+			sleep "${VERACODE_PROBE_SECONDS}" || fail "Sleep interrupted, cannot continue"
 			continue
 			;;
 
@@ -126,20 +131,20 @@ TARGET_BASE="${TARGET_PATH}/${APP_NAME}.scan-report.${VERACODE_BUILD_ID}"
 # Get detailed report as XML
 say "👉 Retrieving the detailed report XML for BUILD_ID = [${VERACODE_BUILD_ID}]..."
 TARGET_XML="${TARGET_BASE}.xml"
-"${VERACODE}" -action DetailedReport -buildid "${VERACODE_BUILD_ID}" -format xml -outputfilepath "${TARGET_XML}" || fail "Failed to retrieve the detailed report XML"
-read SUM REST < <("${SHA256SUM}" "${TARGET_XML}")
+veracode -action DetailedReport -buildid "${VERACODE_BUILD_ID}" -format xml -outputfilepath "${TARGET_XML}" || fail "Failed to retrieve the detailed report XML"
+read SUM REST < <(sha256sum "${TARGET_XML}")
 BYTES="$("${STAT}" -c "%s" "${TARGET_XML}")"
 say "\t✅ Detailed report XML retrieved as [${TARGET_XML}] (size $(printf "%'d" "${BYTES}") bytes, checksum = ${SUM})"
 
 # Get detailed report as PDF
 TARGET_PDF="${TARGET_BASE}.pdf"
 say "👉 Retrieving the detailed report PDF for BUILD_ID = [${VERACODE_BUILD_ID}]..."
-"${VERACODE}" -action DetailedReport -buildid "${VERACODE_BUILD_ID}" -format pdf -outputfilepath "${TARGET_PDF}" || fail "Failed to retrieve the detailed report PDF"
-read SUM REST < <("${SHA256SUM}" "${TARGET_PDF}")
+veracode -action DetailedReport -buildid "${VERACODE_BUILD_ID}" -format pdf -outputfilepath "${TARGET_PDF}" || fail "Failed to retrieve the detailed report PDF"
+read SUM REST < <(sha256sum "${TARGET_PDF}")
 BYTES="$("${STAT}" -c "%s" "${TARGET_PDF}")"
 say "\t✅ Detailed report PDF retrieved as [${TARGET_PDF}] (size $(printf "%'d" "${BYTES}") bytes, checksum = ${SUM})"
 
-SCAN_SCORE="$("${XMLSTARLET}" sel -N "dr=https://www.veracode.com/schema/reports/export/1.0" -t -v "/dr:detailedreport/dr:static-analysis/@score" < "${TARGET_XML}")"
+SCAN_SCORE="$(xmlstarlet sel -N "dr=https://www.veracode.com/schema/reports/export/1.0" -t -v "/dr:detailedreport/dr:static-analysis/@score" < "${TARGET_XML}")"
 say "⚠️ The scan score is ${SCAN_SCORE}"
 
 exit 0
diff --git a/scripts/veracode-get-app-id b/scripts/veracode-get-app-id
--- a/scripts/veracode-get-app-id
+++ b/scripts/veracode-get-app-id
@@ -1,20 +1,29 @@
 #!/bin/bash
 set -euo pipefail
 
-timestamp() {
-	/usr/bin/date -Ins -u
+timestamp()
+{
+	date -Ins -u
 }
 
-say() {
+say()
+{
 	echo -e "$(timestamp): ${@}"
 }
 
-fail() {
-	say "❌ ${@}" 1>&2
+err()
+{
+	say "❌ ${@}"
+}
+
+fail()
+{
+	err "${@}"
 	exit ${EXIT_CODE:-1}
 }
 
-usage() {
+usage()
+{
 	echo -e "usage: ${BASH_ARGV0:-${BASH_SOURCE:-${0}}} appName" 1>&2
 	exit 1
 }
@@ -25,19 +34,16 @@ usage() {
 APP_NAME="${1}"
 [ -n "${APP_NAME}" ] || fail "The application name may not be the empty string"
 
-VERACODE="$(type -P veracode 2>/dev/null)" || fail "The veracode executable could not be found in the PATH"
-XMLSTARLET="$(type -P xmlstarlet 2>/dev/null)" || fail "The xmlstarlet executable could not be found in the PATH"
-
 [ -v VERACODE_API_KEY_ID ] || fail "The VERACODE_API_KEY_ID variable is not set, cannot continue"
 [ -n "${VERACODE_API_KEY_ID}" ] || fail "The VERACODE_API_KEY_ID variable has an empty value, cannot continue"
 [ -v VERACODE_API_KEY_SECRET ] || fail "The VERACODE_API_KEY_SECRET variable is not set, cannot continue"
 [ -n "${VERACODE_API_KEY_SECRET}" ] || fail "The VERACODE_API_KEY_SECRET variable has an empty value, cannot continue"
 
-XML="$("${VERACODE}" -action getapplist)" || fail "Failed to retrieve the application list"
+XML="$(veracode -action getapplist)" || fail "Failed to retrieve the application list"
 
 # Find the application with the correct (case-sensitive) name, and spit
 # out the Application ID
 
-APP_ID="$("${XMLSTARLET}" sel -N "al=https://analysiscenter.veracode.com/schema/2.0/applist" -t -v "/al:applist/al:app[@app_name='${APP_NAME}']/@app_id" <<< "${XML}")" || exit ${?}
+APP_ID="$(xmlstarlet sel -N "al=https://analysiscenter.veracode.com/schema/2.0/applist" -t -v "/al:applist/al:app[@app_name='${APP_NAME}']/@app_id" <<< "${XML}")" || exit ${?}
 echo "${APP_ID}"
 exit 0
diff --git a/scripts/veracode-get-scan-state b/scripts/veracode-get-scan-state
--- a/scripts/veracode-get-scan-state
+++ b/scripts/veracode-get-scan-state
@@ -1,24 +1,33 @@
 #!/bin/bash
-SCRIPT="$(/usr/bin/readlink -f "${BASH_SOURCE:-${0}}")"
-BASEDIR="$(/usr/bin/dirname "${SCRIPT}")"
-SCRIPT="$(/usr/bin/basename "${SCRIPT}")"
+SCRIPT="$(readlink -f "${BASH_SOURCE:-${0}}")"
+BASEDIR="$(dirname "${SCRIPT}")"
+SCRIPT="$(basename "${SCRIPT}")"
 
 set -euo pipefail
 
-timestamp() {
-	/usr/bin/date -Ins -u
+timestamp()
+{
+	date -Ins -u
 }
 
-say() {
+say()
+{
 	echo -e "$(timestamp): ${@}"
 }
 
-fail() {
-	say "❌ ${@}" 1>&2
+err()
+{
+	say "❌ ${@}"
+}
+
+fail()
+{
+	err "${@}"
 	exit ${EXIT_CODE:-1}
 }
 
-usage() {
+usage()
+{
 	echo -e "usage: ${BASH_ARGV0:-${BASH_SOURCE:-${0}}} appId buildId" 1>&2
 	exit 1
 }
@@ -32,9 +41,6 @@ APP_NAME="${1}"
 BUILD_ID="${2}"
 [ -n "${BUILD_ID}" ] || fail "The build id may not be the empty string"
 
-VERACODE="$(type -P veracode 2>/dev/null)" || fail "The veracode executable could not be found in the PATH"
-XMLSTARLET="$(type -P xmlstarlet 2>/dev/null)" || fail "The xmlstarlet executable could not be found in the PATH"
-
 [ -v VERACODE_API_KEY_ID ] || fail "The VERACODE_API_KEY_ID variable is not set, cannot continue"
 [ -n "${VERACODE_API_KEY_ID}" ] || fail "The VERACODE_API_KEY_ID variable has an empty value, cannot continue"
 [ -v VERACODE_API_KEY_SECRET ] || fail "The VERACODE_API_KEY_SECRET variable is not set, cannot continue"
@@ -43,9 +49,9 @@ XMLSTARLET="$(type -P xmlstarlet 2>/dev/null)" || fail "The xmlstarlet executabl
 # Compute the application ID based on the name
 APP_ID="$("${BASEDIR}/veracode-get-app-id" "${APP_NAME}")" || fail "Failed to get the application ID for [${APP_NAME}]"
 
-BUILDINFO="$("${VERACODE}" -action GetBuildInfo -appid "${APP_ID}" -buildid "${BUILD_ID}" -format xml)" || fail "Failed to fetch the build information!"
+BUILDINFO="$(veracode -action GetBuildInfo -appid "${APP_ID}" -buildid "${BUILD_ID}" -format xml)" || fail "Failed to fetch the build information!"
 
-STATUS="$("${XMLSTARLET}" sel -N "bi=https://analysiscenter.veracode.com/schema/4.0/buildinfo" -t -v "/bi:buildinfo/bi:build/bi:analysis_unit/@status" <<< "${BUILDINFO}")" || fail "Failed to get the build status for Application [${APP_NAME}], build [${BUILD_ID}]"
+STATUS="$(xmlstarlet sel -N "bi=https://analysiscenter.veracode.com/schema/4.0/buildinfo" -t -v "/bi:buildinfo/bi:build/bi:analysis_unit/@status" <<< "${BUILDINFO}")" || fail "Failed to get the build status for Application [${APP_NAME}], build [${BUILD_ID}]"
 
 echo "${STATUS}"
 exit 0
diff --git a/scripts/wait-for-pvc-attachments b/scripts/wait-for-pvc-attachments
--- a/scripts/wait-for-pvc-attachments
+++ b/scripts/wait-for-pvc-attachments
@@ -19,7 +19,7 @@ export DISABLE_CLEANUP
 
 timestamp()
 {
-	/usr/bin/date -Ins
+	date -Ins -u
 }
 
 say()
@@ -39,7 +39,7 @@ warn()
 
 err()
 {
-	say "❌ ${@}" 1>&2
+	say "❌ ${@}"
 }
 
 fail()
@@ -173,7 +173,7 @@ is_attachment_valid()
 	local ATTACHED=""
 	local NODE=""
 
-	read ATTACHED NODE < <("${JQ}" -r '(.status.attached | tostring) + " " + .spec.nodeName' <<< "${ATTACHMENT_INFO}")
+	read ATTACHED NODE < <(jq -r '(.status.attached | tostring) + " " + .spec.nodeName' <<< "${ATTACHMENT_INFO}")
 	if [ -z "${ATTACHED}" ] || [ -z "${NODE}" ] ; then
 		# No node info?!?
 		say "\t❌ the attachment [${ATTACHMENT}] has no node information... deleting"
@@ -215,12 +215,6 @@ usage()
 	exit 1
 }
 
-KUBECTL="$(type -P kubectl)" || fail "Could not find 'kubectl' in the path"
-JQ="$(type -P jq)" || fail "Could not find 'jq' in the path"
-SED="$(type -P sed)" || fail "Could not find 'sed' in the path"
-SORT="$(type -P sort)" || fail "Could not find 'sort' in the path"
-TIMEOUT="$(type -P timeout)" || fail "Could not find 'timeout' in the path"
-
 [ ${#} -ge 1 ] && [ ${#} -le 2 ] || usage
 
 CLEANUP_TIMEOUT=$(timestr_to_secs "${CLEANUP_TIMEOUT}") || fail "Invalid value for CLEANUP_TIMEOUT: [${CLEANUP_TIMEOUT}]"
@@ -230,7 +224,7 @@ if [ ${#} -eq 2 ] ; then
 	NAMESPACE="${1}"
 	shift
 elif [ ! -v NAMESPACE ] ; then
-	NAMESPACE="$("${KUBECTL}" config view --minify -o jsonpath="{..namespace}")"
+	NAMESPACE="$(kubectl config view --minify -o jsonpath="{..namespace}")"
 	[ -n "${NAMESPACE}" ] || NAMESPACE="default"
 fi
 is_valid_name "${NAMESPACE}" || fail "The NAMESPACE value [${NAMESPACE}] is not valid"
@@ -238,57 +232,57 @@ is_valid_name "${NAMESPACE}" || fail "The NAMESPACE value [${NAMESPACE}] is not 
 RELEASE="${1}"
 is_valid_name "${RELEASE}" || fail "The RELEASE value [${RELEASE}] is not valid"
 
-"${KUBECTL}" get namespace "${NAMESPACE}" &>/dev/null || fail "The namespace [${NAMESPACE}] does not exist"
+kubectl get namespace "${NAMESPACE}" &>/dev/null || fail "The namespace [${NAMESPACE}] does not exist"
 
 CLEANUP_TIMEOUT_STR="$(secs_to_timestr "${CLEANUP_TIMEOUT}")"
 CLEANUP_RETRY_WAIT_STR="$(secs_to_timestr "${CLEANUP_RETRY_WAIT}")"
 say "⌛ Waiting for the volume attachments to be released (up to ${CLEANUP_TIMEOUT_STR} total)..."
 PREVIOUS_RUN=()
-START="$(/usr/bin/date +%s)"
+START="$(date +%s)"
 while true ; do
 
 	# Get all the PVCs in the currently default namespace
 	say "👀 Fetching all the PVC data on the namespace ${NAMESPACE} for release ${RELEASE}..."
-	PVC_DATA="$("${KUBECTL}" get --namespace "${NAMESPACE}" pvc --selector="app.kubernetes.io/instance=${RELEASE}" -o json)"
+	PVC_DATA="$(kubectl get --namespace "${NAMESPACE}" pvc --selector="app.kubernetes.io/instance=${RELEASE}" -o json)"
 	say "👀 Fetching all the PV data on cluster..."
-	PV_DATA="$("${KUBECTL}" get pv -o json)"
+	PV_DATA="$(kubectl get pv -o json)"
 	say "👀 Fetching all the Node data on the cluster..."
-	NODE_DATA="$("${KUBECTL}" get node -o json)"
+	NODE_DATA="$(kubectl get node -o json)"
 
-	PVC_COUNT="$("${JQ}" -r ".items | length" <<< "${PVC_DATA}")"
+	PVC_COUNT="$(jq -r ".items | length" <<< "${PVC_DATA}")"
 
 	ok "Found ${PVC_COUNT} PVCs"
 	[ ${PVC_COUNT} -gt 0 ] || exit 0
 
-	readarray -t PVCS < <("${JQ}" -r ".items[] | .metadata.name" <<< "${PVC_DATA}" | "${SORT}" -u)
+	readarray -t PVCS < <(jq -r ".items[] | .metadata.name" <<< "${PVC_DATA}" | sort -u)
 
 	say "👀 Fetching all the Volume Attachment data on the cluster..."
-	ATTACHMENT_DATA="$("${KUBECTL}" get "${ATTACHMENT_RESOURCE}" -o json)"
+	ATTACHMENT_DATA="$(kubectl get "${ATTACHMENT_RESOURCE}" -o json)"
 
 	(( BROKEN=0 )) || true
 	CURRENT_RUN=()
 	for PVC in "${PVCS[@]}" ; do
 
-		PVC_INFO="$("${JQ}" -r ".items[] | select(.metadata.name == \"${PVC}\")" <<< "${PVC_DATA}")"
+		PVC_INFO="$(jq -r ".items[] | select(.metadata.name == \"${PVC}\")" <<< "${PVC_DATA}")"
 
-		PV="$("${JQ}" -r ".spec.volumeName" <<< "${PVC_INFO}")"
-		PV_INFO="$("${JQ}" -r ".items[] | select(.metadata.name == \"${PV}\")" <<< "${PV_DATA}")"
+		PV="$(jq -r ".spec.volumeName" <<< "${PVC_INFO}")"
+		PV_INFO="$(jq -r ".items[] | select(.metadata.name == \"${PV}\")" <<< "${PV_DATA}")"
 		if [ -z "${PV}" ] || [ -z "${PV_INFO}" ] ; then
 			err "No volume ${PV} found ... referenced by PVC ${PVC}"
 			continue
 		fi
 
 		# For each PVC, identify the pod(s) it's attached to
-		readarray -t ATTACHMENTS < <("${JQ}" -r ".items[] | select(.spec.source.persistentVolumeName == \"${PV}\") | .metadata.name" <<< "${ATTACHMENT_DATA}")
+		readarray -t ATTACHMENTS < <(jq -r ".items[] | select(.spec.source.persistentVolumeName == \"${PV}\") | .metadata.name" <<< "${ATTACHMENT_DATA}")
 
 		[ "${#ATTACHMENTS[@]}" -gt 0 ] || continue
 
 		say "👀 Found ${#ATTACHMENTS[@]} attachments for ${PVC}"
 		for ATTACHMENT in "${ATTACHMENTS[@]}" ; do
-			ATTACHMENT_INFO="$("${JQ}" -r ".items[] | select(.metadata.name == \"${ATTACHMENT}\")" <<< "${ATTACHMENT_DATA}")"
-			NODE="$("${JQ}" -r '.spec.nodeName' <<< "${ATTACHMENT_INFO}")"
+			ATTACHMENT_INFO="$(jq -r ".items[] | select(.metadata.name == \"${ATTACHMENT}\")" <<< "${ATTACHMENT_DATA}")"
+			NODE="$(jq -r '.spec.nodeName' <<< "${ATTACHMENT_INFO}")"
 
-			NODE_INFO="$("${JQ}" -r ".items[] | select(.metadata.name == \"${NODE}\")" <<< "${NODE_DATA}")"
+			NODE_INFO="$(jq -r ".items[] | select(.metadata.name == \"${NODE}\")" <<< "${NODE_DATA}")"
 
 			ATTACHMENT_REF="${PVC}/${PV}/${ATTACHMENT}/${NODE}"
 			OK="true"
@@ -309,7 +303,7 @@ while true ; do
 	say "👉 Found ${#CURRENT_RUN[@]} that are still pending removal (${BROKEN} appear to be broken)..."
 
 	# There are still some ... have we timed out yet?
-	NOW="$(/usr/bin/date +%s)"
+	NOW="$(date +%s)"
 	(( DIFF = ( NOW - START ) )) || true
 	[ ${DIFF} -lt ${CLEANUP_TIMEOUT} ] || fail_for_timeout "${CURRENT_RUN[@]}"
 
@@ -326,7 +320,7 @@ while true ; do
 	fi
 
 	say "💤 Will wait ${CLEANUP_RETRY_WAIT_STR} before the next attempt..."
-	/usr/bin/sleep ${CLEANUP_RETRY_WAIT} || fail "Sleep interrupted - cannot continue!"
+	sleep ${CLEANUP_RETRY_WAIT} || fail "Sleep interrupted - cannot continue!"
 
 done
 exit 0
