Two important fixes (see below):
- Don't wait for the artifacts pod to be ready before getting the checksums because the pod may be down, so waiting for it to be up is not necessary. There are two scenarios:
     - The deployment is started with the artifacts pod running, in which case we need not wait to get the checksums on the initial pass
     - The deployment is started without the artifacts pod running, in which case we simply assume that a new artifacts pod is being deployed. If we were to try to scale up that deployment beforehand it might muck up the works, so if it's down we simply assume that we can't get the checksums and proceed accordingly. Regardless, the script will no longer hang/fail if the artifacts pod isn't running at deployment time.

- Don't "update" the value of the "OLD_SUMS" on the smart rollover. When comparing the UIDs for the "smart rollover", we were updating the OLD_UID list with the new value for the NEW_UIDs. That could cause a loop where it perpetually found pods that needed bouncing. The OLD_UID list contains the IDs for the pods at the start fo the deployment, and the goal of the smart rollover is to see all the necessary UIDs change from those values. If we continually update the value from NEW_UID, we'll continually find pods that "didn't roll over" because the script thinks the updated OLD_UID is the original pre-deployment, which is wrong b/c it would have been updated already with pods that were deleted.

diff --git a/scripts/deploy-environment b/scripts/deploy-environment
--- a/scripts/deploy-environment
+++ b/scripts/deploy-environment
@@ -120,10 +120,16 @@ render_artifacts_selector()
 	render_selector "${1}" "${ARTIFACTS_EXTRA_SELECTOR}"
 }
 
+get_global_sums_nowait()
+{
+	get_global_sums "${1}" "${2}" "false"
+}
+
 get_global_sums()
 {
 	local NAMESPACE="${1}"
 	local RELEASE="${2}"
+	local WAIT_READY="${3:-"true"}"
 	local SELECTOR="$(render_artifacts_selector "${RELEASE}")"
 	local POD=""
 
@@ -133,7 +139,9 @@ get_global_sums()
 	local ERRORS=()
 	while read POD ; do
 		# First, wait for the pod to become ready ... up to 5 mins
-		kubectl --namespace "${NAMESPACE}" wait --for condition=Ready "${POD}" --timeout=5m &>/dev/null || continue
+		if as_boolean "${WAIT_READY}" ; then
+			kubectl --namespace "${NAMESPACE}" wait --for condition=Ready "${POD}" --timeout=5m &>/dev/null || continue
+		fi
 
 		# Run the sums. We do this in case networking is not
 		# available to us. We know kubectl *is*, so use that!
@@ -143,7 +151,7 @@ get_global_sums()
 		SUM="$(timeout 30 kubectl --namespace "${NAMESPACE}" exec "${POD}" -- /usr/local/bin/global-sums 2>&1)" || RC=${?}
 		if [ ${RC} -ne 0 ] ; then
 			ERRORS+=( "$(timestamp) ${RC} ${SUM}" )
-			continue
+			as_boolean "${WAIT_READY}" && continue || break
 		fi
 
 		# The output must not be empty
@@ -181,7 +189,8 @@ list_pod_uids()
 	local NAMESPACE="${1}"
 	local RELEASE="${2}"
 	local SELECTOR="$(render_selector "${RELEASE}" "${3:-}")"
-	kubectl --namespace "${NAMESPACE}" get pod --selector "${SELECTOR}" -o json | jq -r '.items[].metadata | .uid + " " + .name'
+	local COLUMNS="UID:.metadata.uid,NAME:.metadata.name"
+	kubectl --namespace "${NAMESPACE}" get pod --selector "${SELECTOR}" --no-headers --output custom-columns="${COLUMNS}"
 }
 
 list_artifact_uids()
@@ -249,8 +258,8 @@ list_unchanged_pods()
 			# If the pod existed, and there's no change in the UID, then
 			# the pod needs to be rolled, so add it to the list!
 			[ -n "${OLD_UID}" ] && [ "${OLD_UID}" == "${NEW_UID}" ] && echo -e "${POD}"
-		done < <(kubectl --namespace "${NAMESPACE}" get pods --selector "${DEPLOY_LABEL}-${CATEGORY}=true" -o name | sed -e 's;^pod/;;g')
-	done | sort -u | sed -e '/^\s*$/d'
+		done < <(kubectl --namespace "${NAMESPACE}" get pods --selector "${DEPLOY_LABEL}-${CATEGORY}=true" --no-headers --output custom-columns=NAME:.metadata.name)
+	done | sort -u
 	return 0
 }
 
@@ -308,6 +317,7 @@ smart_rollover()
 	local MAX_ATTEMPTS=5
 	local ROLL=()
 	local NEW_PODS=""
+	local RC=0
 	while true ; do
 		NEW_PODS="$(list_consumer_uids "${NAMESPACE}" "${RELEASE}")"
 
@@ -336,8 +346,17 @@ smart_rollover()
 		execute timeout --signal=TERM --kill-after=5m 4m kubectl --namespace "${NAMESPACE}" --ignore-not-found --timeout=3m delete pod "${ROLL[@]}" || err "kubectl command failed (rc=${?})"
 		# Regardless of whether this command failed, we want to check the actual result
 
+		# Wait until the deleted pods disappear
+		RC=0
+		execute timeout --signal=TERM --kill-after=5m 4m kubectl --namespace "${NAMESPACE}" --ignore-not-found --timeout=3m wait --for=delete pod "${ROLL[@]}" || RC=${?}
+		if [ ${RC} -ne 0 ] ; then
+			err "Failed to wait for the pods ${ROLL[@]} to be deleted ... will wait 30 seconds as a safety precaution (rc=${RC})"
+			if ! sleep 30s ; then
+				err "Sleep interrupted - returning immediately!"
+				return 1
+			fi
+		fi
 		(( ++ATTEMPT ))
-		OLD_PODS="${NEW_PODS}"
 	done
 }
 
@@ -481,7 +500,7 @@ else
 	fi
 
 	RC=0
-	OLD_ARTIFACTS="$(get_global_sums "${NAMESPACE}" "${RELEASE}" 2>&1)" || RC=${?}
+	OLD_ARTIFACTS="$(get_global_sums_nowait "${NAMESPACE}" "${RELEASE}" 2>&1)" || RC=${?}
 	if [ ${RC} -ne 0 ] ; then
 		warn "Failed to fetch the old artifact checksums (rc=${RC}):\n${OLD_ARTIFACTS}"
 		OLD_ARTIFACTS="{}"
