Added enhancements for deployment and undeployment

diff --git a/scripts/deploy-environment b/scripts/deploy-environment
--- a/scripts/deploy-environment
+++ b/scripts/deploy-environment
@@ -212,13 +212,34 @@ fi
 
 ensure_namespace_exists "${NAMESPACE}" || fail "Failed to ensure that the required namespace ${NAMESPACE} exists"
 
-# Delete the old installation, since it's the safest bet to ensure
-# that the correct resources, containers, and deployments are used
+set -- "${HELM_ARGS[@]}"
+
+#
+# First, try an in-place upgrade. If that fails, then undeploy and redeploy
+#
+RC=0
+execute \
+	helm upgrade --install \
+		"${RELEASE}" "${CHART}" \
+		--namespace "${NAMESPACE}" \
+		--wait \
+		--timeout "${DEPLOY_TIMEOUT}" \
+		"${VALUES[@]}" \
+		"${@}" || RC=${?}
+
+if [ ${RC} -eq 0 ] ; then
+	ok "Deployment complete!"
+	execute kubectl --namespace "${NAMESPACE}" get pods
+	exit ${RC}
+fi
+
+err "In-place upgrade failed, will try to uninstall and reinstall"
+
+# The in-place upgrade failed ... we need to fully uninstall and
+# then re-install the application!
 #
 # Propagate the "disable" flag, to do nothing if we're testing
 DISABLE_UNDEPLOY="${DISABLE_DEPLOY}" "${BASEDIR}/undeploy-environment" "${NAMESPACE}" "${RELEASE}" || exit ${?}
-
-set -- "${HELM_ARGS[@]}"
 
 # Execute the new installation, using install --replace
 # because we intend to be preserving history from our
