Gated the in-place upgrade until we figure out the pod rolls

diff --git a/scripts/deploy-environment b/scripts/deploy-environment
--- a/scripts/deploy-environment
+++ b/scripts/deploy-environment
@@ -14,6 +14,13 @@ case "${DISABLE_DEPLOY,,}" in
 esac
 export DISABLE_DEPLOY
 
+[ -v PARTIAL_DEPLOYMENT ] || PARTIAL_DEPLOYMENT="false"
+case "${PARTIAL_DEPLOYMENT,,}" in
+	true | t | yes | y ) PARTIAL_DEPLOYMENT="true" ;;
+	* ) PARTIAL_DEPLOYMENT="false" ;;
+esac
+export PARTIAL_DEPLOYMENT
+
 timestamp()
 {
 	date -Ins -u
@@ -110,6 +117,67 @@ sanitize_common_dirs()
 		fi
 		echo "${C}"
 	done
+}
+
+get_artifacts_selector()
+{
+	local RELEASE="${1}"
+	echo -n "app.kubernetes.io/instance=${RELEASE},app.kubernetes.io/name=app,app.kubernetes.io/part=artifacts"
+}
+
+get_artifacts_image()
+{
+	local RELEASE="${1}"
+	local JQ_EXP='.items[] | .status.containerStatuses[] | select(.name == "artifacts") | .imageID'
+	kubectl get pod -l "$(get_artifacts_selector "${RELEASE}")"  -o json | jq -r "${JQ_EXP}" | sort -u
+}
+
+roll_pods_if_necessary()
+{
+	local RELEASE="${1}"
+	local OLD="${2}"
+
+	# Roll the artifacts pod, and wait for it to be ready again...
+	local SELECTOR="$(get_artifacts_selector "${RELEASE}")"
+
+	# Roll the pod
+	if execute kubectl delete pod -l "${SELECTOR}" ; then
+		err "Failed to roll the artifacts pod (selector = [${SELECTOR}])"
+		return 0
+	fi
+
+	# Wait for it to be ready
+	if ! kubectl wait --for=condition=Initialized pod -l "${SELECTOR}" --timeout 5m ; then
+		err "The artifacts pod failed to be initialized in the allowed timeframe - can't check the image"
+		return 0
+	fi
+
+	# Get the new image
+	local NEW="$(get_artifacts_image "${RELEASE}")"
+
+	# If the new one is blank, we don't need to roll anything
+	[ -n "${NEW}" ] || return 0
+
+	# If they're the same, there's no need to roll anything
+	[ "${OLD}" != "${NEW}" ] || return 0
+
+	# If they're different, then def we should roll whatever needs rolling
+
+	# TODO: Shall we check each dependent pod in turn to see if rolling is needed? How?
+
+	SELECTOR="app.kubernetes.io/instance=${RELEASE},arkcase.com/pod-depends=artifacts"
+	if ! execute kubectl delete pod -l "${SELECTOR}" ; then
+		err "Failed to roll the dependent pods (selector = [${SELECTOR}])"
+		return 0
+	fi
+
+	if ! kubectl wait --for=condition=Ready pod -l "${SELECTOR}" --timeout "${DEPLOY_TIMEOUT}" ; then
+		err "The artifact-dependent pods did not become ready after the stipulated timeout (${DEPLOY_TIMEOUT}, selector = [${SELECTOR}])"
+		return 0
+	fi
+
+	ok "Rolled all pods dependent on the artifacts pod"
+	return 0
 }
 
 usage()
@@ -215,25 +283,46 @@ ensure_namespace_exists "${NAMESPACE}" || fail "Failed to ensure that the requir
 set -- "${HELM_ARGS[@]}"
 
 #
-# First, try an in-place upgrade. If that fails, then undeploy and redeploy
+# We use this to gate partial deployments (i.e. in-place upgrades)
+# b/c we haven't yet fully figured out how to properly handle those.
 #
-RC=0
-execute \
-	helm upgrade --install \
-		"${RELEASE}" "${CHART}" \
-		--namespace "${NAMESPACE}" \
-		--wait \
-		--timeout "${DEPLOY_TIMEOUT}" \
-		"${VALUES[@]}" \
-		"${@}" || RC=${?}
+if "${PARTIAL_DEPLOYMENT}" ; then
 
-if [ ${RC} -eq 0 ] ; then
-	ok "Deployment complete!"
-	execute kubectl --namespace "${NAMESPACE}" get pods
-	exit ${RC}
+	# Take note of the container image that's currently in use by the
+	# artifacts pod, so we can determine if dependent pods need to be
+	# rolled later
+	OLD_ARTIFACTS="$(get_artifacts_image "${RELEASE}")"
+
+	#
+	# TODO: one possible way to identify pods that need to be rolled is by
+	# comparing their "Initialized" timestamp to the artifacts pod's
+	# "Ready" timestamp. If they were initialized before the new artifacts
+	# pod became ready, then clearly they will have to be rolled so they
+	# can consume the new artifacts.
+	#
+
+	#
+	# First, try an in-place upgrade. If that fails, then undeploy and redeploy
+	#
+	RC=0
+	execute \
+		helm upgrade --install \
+			"${RELEASE}" "${CHART}" \
+			--namespace "${NAMESPACE}" \
+			--wait \
+			--timeout "${DEPLOY_TIMEOUT}" \
+			"${VALUES[@]}" \
+			"${@}" || RC=${?}
+
+	if [ ${RC} -eq 0 ] ; then
+		ok "Deployment complete!"
+		roll_pods_if_necessary "${RELEASE}" "${OLD_ARTIFACTS}"
+		execute kubectl --namespace "${NAMESPACE}" get pods
+		exit ${RC}
+	fi
+
+	err "In-place upgrade failed, will try to uninstall and reinstall"
 fi
-
-err "In-place upgrade failed, will try to uninstall and reinstall"
 
 # The in-place upgrade failed ... we need to fully uninstall and
 # then re-install the application!
