FEATURE: make all scripts use --repo|-R
The only exception is for gh-workflow-run-and-wait

diff --git a/scripts/gh-workflow-run b/scripts/gh-workflow-run
--- a/scripts/gh-workflow-run
+++ b/scripts/gh-workflow-run
@@ -21,7 +21,7 @@ usage()
 ARGS="$(getopt -o "r:R:h?" -l "help,ref:,repo:" -n "${BASH_ARGV0:-${BASH_SOURCE:-${0}}}" -- "${@}")" || usage
 
 REPO=()
-REPO_PARAM=()
+REPO_NAME=()
 REPO_SET="false"
 REF=()
 REF_SET="false"
@@ -35,8 +35,8 @@ while true ; do
 		-R | --repo )
 			as_boolean "${REPO_SET}" && fail "You may specify ${1} only once"
 			[ -n "${2}" ] || fail "The target repository may not be the empty string (${1})"
-			REPO=("${2}")
-			REPO_PARAM=(--repo "${2}")
+			REPO=(--repo "${2}")
+			REPO_NAME=("${2}")
 			REPO_SET="true"
 			shift 2
 			continue
@@ -59,7 +59,7 @@ while true ; do
 	esac
 done
 
-[ ${#} -ge 1 ] || usage "You must specify the name of the workflow to run"
+[ ${#} -ge 1 ] || usage
 
 WORKFLOW="${1}"
 [ -n "${WORKFLOW}" ] || fail "The workflow may not be an empty string"
@@ -75,7 +75,7 @@ done
 GH_USER_FLAGS=()
 [ -v GH_WORKFLOW_USER ] && [ "${GH_WORKFLOW_USER:-""}" ] && GH_USER_FLAGS=(--user "${GH_WORKFLOW_USER}")
 
-PROJECT="$(gh repo view "${REPO[@]}" --json nameWithOwner --jq .nameWithOwner)" || fail "Unable to identify the GitHub project"
+PROJECT="$(gh repo view "${REPO_NAME[@]}" --json nameWithOwner --jq .nameWithOwner)" || fail "Unable to identify the GitHub project"
 
 say "👉 Launching the GH Workflow [${WORKFLOW}]"
 for p in "${PARAMS[@]}" ; do
@@ -83,7 +83,7 @@ for p in "${PARAMS[@]}" ; do
 	say "\t${p}"
 done
 START="$(date -Is -u)"
-gh workflow run "${WORKFLOW}" "${REF[@]}" "${REPO_PARAM[@]}" "${PARAMS[@]}" || fail "Failed to launch the workflow run!"
+gh workflow run "${WORKFLOW}" "${REF[@]}" "${REPO[@]}" "${PARAMS[@]}" || fail "Failed to launch the workflow run!"
 say "\t✅ Workflow launched!"
 
 # This is unelegant, but appears to be necessary
@@ -98,7 +98,7 @@ while true ; do
 	# concurrently.
 	RUN_ID="$(
 		gh run list \
-			"${REPO_PARAM[@]}" \
+			"${REPO[@]}" \
 			"${GH_USER_FLAGS[@]}" \
 			--event workflow_dispatch \
 			--created "${START}..$(date -Is -u)" \
@@ -114,7 +114,7 @@ done
 
 # Wait for the run to complete
 say "\t✅ Workflow started with run ID [${RUN_ID}]..."
-if URL="$(gh run view "${RUN_ID}" "${REPO_PARAM[@]}" --json url --jq .url 2>&1)" ; then
+if URL="$(gh run view "${RUN_ID}" "${REPO[@]}" --json url --jq .url 2>&1)" ; then
 	say "\t✅ Workflow Run URL: ${URL}"
 	URL="${URL}"
 else
diff --git a/scripts/gh-workflow-watch b/scripts/gh-workflow-watch
--- a/scripts/gh-workflow-watch
+++ b/scripts/gh-workflow-watch
@@ -5,19 +5,29 @@ set -euo pipefail
 
 usage()
 {
-	echo -e "usage: ${BASH_ARGV0:-${BASH_SOURCE:-${0}}} [ repository ] workflow runid"
+	[ ${#} -eq 0 ] || echo -e "❌ ${@}\n"
+	echo -e "usage: ${BASH_ARGV0:-${BASH_SOURCE:-${0}}} [ -R | --repo repository ] workflow runId"
 	exit 1
 }
 
-[ ${#} -ge 2 ] || usage
-[ ${#} -le 3 ] || usage
-
-ARGS="$(getopt -o "h?" -l "help" -n "${BASH_ARGV0:-${BASH_SOURCE:-${0}}}" -- "${@}")" || usage
+ARGS="$(getopt -o "R:h?" -l "help,repo:" -n "${BASH_ARGV0:-${BASH_SOURCE:-${0}}}" -- "${@}")" || usage
 
 eval set -- "${ARGS}"
 
+REPO=()
+REPO_SET="false"
+
 while true ; do
 	case "${1}" in
+		-R | --repo )
+			as_boolean "${REPO_SET}" && fail "You may specify ${1} only once"
+			[ -n "${2}" ] || fail "The repository may not be the empty string (${1})"
+			REPO=(--repo "${2}")
+			REPO_SET="true"
+			shift 2
+			continue
+			;;
+
 		--help | -h | "-?" ) usage ;;
 
 		-- ) shift ; break ;;
@@ -26,30 +36,25 @@ while true ; do
 	esac
 done
 
-REPO_PARAM=()
-if [ ${#} -eq 3 ] ; then
-	[ -n "${1}" ] || fail "The repository name may not be an empty string"
-	REPO_PARAM=(--repo "${1}")
-	shift
-fi
+[ ${#} -eq 2 ] || usage
 
 WORKFLOW="${1}"
-[ -n "${WORKFLOW}" ] || fail "The workflow may not be an empty string"
+[ -n "${WORKFLOW}" ] || usage "The workflow may not be an empty string"
 RUN_ID="${2}"
-[ -n "${RUN_ID}" ] || fail "The runId may not be an empty string"
+[ -n "${RUN_ID}" ] || usage "The runId may not be an empty string"
 
 GH_USER_FLAGS=()
 [ -v GH_WORKFLOW_USER ] && [ "${GH_WORKFLOW_USER:-""}" ] && GH_USER_FLAGS=(--user "${GH_WORKFLOW_USER}")
 
 # Wait for the run to complete
 say "\t👀 Watching run # ${RUN_ID} for workflow ${WORKFLOW}..."
-gh run watch "${RUN_ID}" "${REPO_PARAM[@]}" || fail "Failed to watch run # ${RUN_ID} to completion"
+gh run watch "${RUN_ID}" "${REPO[@]}" || fail "Failed to watch run # ${RUN_ID} to completion"
 
 RC=0
-gh run view "${RUN_ID}" "${REPO_PARAM[@]}" --exit-status &>/dev/null || RC="${?}"
+gh run view "${RUN_ID}" "${REPO[@]}" --exit-status &>/dev/null || RC="${?}"
 
 # Always show the full log
-gh run view "${RUN_ID}" "${REPO_PARAM[@]}" --log
+gh run view "${RUN_ID}" "${REPO[@]}" --log
 
 [ ${RC} -eq 0 ] || fail "Run ${RUN_ID} failed! (rc = ${RC})"
 say "✅ Run ${RUN_ID} succeeded!"
