BUG: NPM_PUBLISH_PASS -> NPM_PUBLISH_PASSWORD

diff --git a/scripts/npm-publish-configure b/scripts/npm-publish-configure
--- a/scripts/npm-publish-configure
+++ b/scripts/npm-publish-configure
@@ -23,11 +23,11 @@ set_or_default NPM_PUBLISH_URL
 [ -z "${NPM_PUBLISH_URL}" ] && quit "The NPM_PUBLISH_URL variable is empty, cannot configure NodeJS deployment"
 [[ "${NPM_PUBLISH_URL}" =~ ^https?://[-a-zA-Z0-9]+(\.[-a-zA-Z0-9]+)*(/.*)?$ ]] || fail "The NPM_PUBLISH_URL value [${NPM_PUBLISH_URL}] is not a valid URL"
 
-set_or_default NPM_PUBLISH_TOKEN ""
+set_or_default NPM_PUBLISH_TOKEN
 set_or_default NPM_PUBLISH_USERNAME
 set_or_default NPM_PUBLISH_PASSWORD
 if [ -z "${NPM_PUBLISH_TOKEN}" ] && [ -n "${NPM_PUBLISH_USERNAME}" ] ; then
-	[ -z "${NPM_PUBLISH_PASS}" ] || fail "If authentication is required, a password must be used"
+	[ -z "${NPM_PUBLISH_PASSWORD}" ] || fail "If authentication is required, a password must be used"
 	NPM_PUBLISH_TOKEN="$(echo -n "${NPM_PUBLISH_USERNAME}:${NPM_PUBLISH_PASSWORD}" | base64)"
 fi
 
