Add generalized NPM authentication support
- This solves the general problem of defining private repositories from whence NPM artifacts will need to be pulled which require authentication

diff --git a/scripts/npm-publish-configure b/scripts/npm-publish-configure
--- a/scripts/npm-publish-configure
+++ b/scripts/npm-publish-configure
@@ -23,20 +23,15 @@ set_or_default NPM_PUBLISH_URL
 [ -z "${NPM_PUBLISH_URL}" ] && quit "The NPM_PUBLISH_URL variable is empty, cannot configure NodeJS deployment"
 [[ "${NPM_PUBLISH_URL}" =~ ^https?://[-a-zA-Z0-9]+(\.[-a-zA-Z0-9]+)*(/.*)?$ ]] || fail "The NPM_PUBLISH_URL value [${NPM_PUBLISH_URL}] is not a valid URL"
 
-set_or_default NPM_PUBLISH_TOKEN
-set_or_default NPM_PUBLISH_USERNAME
-set_or_default NPM_PUBLISH_PASSWORD
-if [ -z "${NPM_PUBLISH_TOKEN}" ] && [ -n "${NPM_PUBLISH_USERNAME}" ] ; then
-	[ -n "${NPM_PUBLISH_PASSWORD}" ] || fail "If authentication is required, a password must be used"
-	NPM_PUBLISH_TOKEN="$(echo -n "${NPM_PUBLISH_USERNAME}:${NPM_PUBLISH_PASSWORD}" | base64)"
-fi
+(
+	for P in URL TOKEN USERNAME PASSWORD ; do
+		V="NPM_PUBLISH_${P}"
+		[ -v "${V}" ] || continue
+		declare -xg "NPM_AUTH_PUBLISH_${P}=${!V}"
+	done
 
-# Remove the scheme, if present...
-NPM_PUBLISH_PREFIX="${NPM_PUBLISH_URL}"
-[[ "${NPM_PUBLISH_PREFIX}" =~ ^https?:(//.*) ]] && NPM_PUBLISH_PREFIX="${BASH_REMATCH[1]}"
-# Add a final slash, if necessary
-[[ "${NPM_PUBLISH_PREFIX}" =~ /$ ]] || NPM_PUBLISH_PREFIX+="/"
+	exec npm-auth-configure
+) || fail "Failed to configure authentication for the scope [${SCOPE}] at [${NPM_PUBLISH_URL}]!"
 
 npm-config set "${SCOPE}:registry=${NPM_PUBLISH_URL}"
-npm-config set "${NPM_PUBLISH_PREFIX}:_auth=${NPM_PUBLISH_TOKEN}"
-quit "Configuration set!"
+ok "Associated the scope [${SCOPE}] with the URL [${NPM_PUBLISH_URL}]!"
