Bolstered security by not exposing credentials

diff --git a/scripts/rancher-get-cluster-id b/scripts/rancher-get-cluster-id
--- a/scripts/rancher-get-cluster-id
+++ b/scripts/rancher-get-cluster-id
@@ -20,6 +20,24 @@ fail()
 	exit ${EXIT_CODE:-1}
 }
 
+auth_params()
+{
+	local USER="${1}"
+	local PASS=""
+
+	if [ ${#} -eq 1 ] ; then
+		[[ "${USER}" =~ ^([^:]*)(:(.*))?$ ]] || true
+		USER="${BASH_REMATCH[1]}"
+		PASS="${BASH_REMATCH[3]}"
+	else
+		PASS="${2}"
+	fi
+
+	"${CAT}" <<-EOF
+	user "${USER}:${PASS}"
+	EOF
+}
+
 usage()
 {
 	echo -e "usage: ${BASH_ARGV0:-${BASH_SOURCE:-${0}}} cluster-name"
@@ -50,8 +68,9 @@ CLUSTER_NAME="${1}"
 
 CURL="$(type -P curl)" || fail "Could not find 'curl' in the path"
 JQ="$(type -P jq)" || fail "Could not find 'jq' in the path"
+CAT="$(type -P cat)" || fail "Could not find 'cat' in the path"
 
-CLUSTER_ID="$("${CURL}" -fsSL -u "${RANCHER_TOKEN}" "${RANCHER_API_ENDPOINT}" | "${JQ}" -r ".data[] | select(.name == \"${CLUSTER_NAME}\") | .id")" || fail "Failed to query the cluster ID for [${CLUSTER_NAME}] (rc=${?})"
+CLUSTER_ID="$("${CURL}" -fsSL --config <(auth_params "${RANCHER_TOKEN}") "${RANCHER_API_ENDPOINT}" | "${JQ}" -r ".data[] | select(.name == \"${CLUSTER_NAME}\") | .id")" || fail "Failed to query the cluster ID for [${CLUSTER_NAME}] (rc=${?})"
 [ -n "${CLUSTER_ID}" ] || fail "No cluster ID was returned for [${CLUSTER_NAME}]"
 echo "${CLUSTER_ID}"
 exit 0
diff --git a/scripts/rancher-get-clusters b/scripts/rancher-get-clusters
--- a/scripts/rancher-get-clusters
+++ b/scripts/rancher-get-clusters
@@ -20,6 +20,24 @@ fail()
 	exit ${EXIT_CODE:-1}
 }
 
+auth_params()
+{
+	local USER="${1}"
+	local PASS=""
+
+	if [ ${#} -eq 1 ] ; then
+		[[ "${USER}" =~ ^([^:]*)(:(.*))?$ ]] || true
+		USER="${BASH_REMATCH[1]}"
+		PASS="${BASH_REMATCH[3]}"
+	else
+		PASS="${2}"
+	fi
+
+	"${CAT}" <<-EOF
+	user "${USER}:${PASS}"
+	EOF
+}
+
 #
 # Make sure we're given a solid token
 #
@@ -40,7 +58,8 @@ RANCHER_API_ENDPOINT="${BASH_REMATCH[0]}/v3/clusters"
 CURL="$(type -P curl)" || fail "Could not find 'curl' in the path"
 SORT="$(type -P sort)" || fail "Could not find 'sort' in the path"
 JQ="$(type -P jq)" || fail "Could not find 'jq' in the path"
+CAT="$(type -P cat)" || fail "Could not find 'cat' in the path"
 
-LIST="$("${CURL}" -fsSL -u "${RANCHER_TOKEN}" "${RANCHER_API_ENDPOINT}" | "${JQ}" -r ".data[] | .id + \" \" + .name")" || fail "Failed to query the cluster list (rc=${?})"
+LIST="$("${CURL}" -fsSL --config <(auth_params "${RANCHER_TOKEN}") "${RANCHER_API_ENDPOINT}" | "${JQ}" -r ".data[] | .id + \" \" + .name")" || fail "Failed to query the cluster list (rc=${?})"
 echo "${LIST}" | "${SORT}" -k 2
 exit 0
diff --git a/scripts/rancher-get-kubeconfig b/scripts/rancher-get-kubeconfig
--- a/scripts/rancher-get-kubeconfig
+++ b/scripts/rancher-get-kubeconfig
@@ -20,6 +20,24 @@ fail()
 	exit ${EXIT_CODE:-1}
 }
 
+auth_params()
+{
+	local USER="${1}"
+	local PASS=""
+
+	if [ ${#} -eq 1 ] ; then
+		[[ "${USER}" =~ ^([^:]*)(:(.*))?$ ]] || true
+		USER="${BASH_REMATCH[1]}"
+		PASS="${BASH_REMATCH[3]}"
+	else
+		PASS="${2}"
+	fi
+
+	"${CAT}" <<-EOF
+	user "${USER}:${PASS}"
+	EOF
+}
+
 usage()
 {
 	echo -e "usage: ${BASH_ARGV0:-${BASH_SOURCE:-${0}}} cluster-name [target-file]"
@@ -59,9 +77,10 @@ fi
 
 CURL="$(type -P curl)" || fail "Could not find 'curl' in the path"
 JQ="$(type -P jq)" || fail "Could not find 'jq' in the path"
+CAT="$(type -P cat)" || fail "Could not find 'cat' in the path"
 
 CLUSTER_ID="$("${BASEDIR}/rancher-get-cluster-id" "${CLUSTER_NAME}")" || exit 1
-CLUSTER_CONFIG="$("${CURL}" -fsSL -X POST -u "${RANCHER_TOKEN}" "${RANCHER_API_ENDPOINT}/${CLUSTER_ID}?action=generateKubeconfig" | jq -r ".config")" || fail "Failed to retrieve the cluster configuration for cluster [${CLUSTER_NAME}](${CLUSTER_ID})"
+CLUSTER_CONFIG="$("${CURL}" -fsSL -X POST --config <(auth_params "${RANCHER_TOKEN}") "${RANCHER_API_ENDPOINT}/${CLUSTER_ID}?action=generateKubeconfig" | jq -r ".config")" || fail "Failed to retrieve the cluster configuration for cluster [${CLUSTER_NAME}](${CLUSTER_ID})"
 
 #
 # Write to STDOUT
diff --git a/scripts/rancher-get-project-id b/scripts/rancher-get-project-id
--- a/scripts/rancher-get-project-id
+++ b/scripts/rancher-get-project-id
@@ -20,6 +20,24 @@ fail()
 	exit ${EXIT_CODE:-1}
 }
 
+auth_params()
+{
+	local USER="${1}"
+	local PASS=""
+
+	if [ ${#} -eq 1 ] ; then
+		[[ "${USER}" =~ ^([^:]*)(:(.*))?$ ]] || true
+		USER="${BASH_REMATCH[1]}"
+		PASS="${BASH_REMATCH[3]}"
+	else
+		PASS="${2}"
+	fi
+
+	"${CAT}" <<-EOF
+	user "${USER}:${PASS}"
+	EOF
+}
+
 usage()
 {
 	echo -e "usage: ${BASH_ARGV0:-${BASH_SOURCE:-${0}}} cluster-name project-name"
@@ -53,9 +71,10 @@ PROJECT_NAME="${2}"
 
 CURL="$(type -P curl)" || fail "Could not find 'curl' in the path"
 JQ="$(type -P jq)" || fail "Could not find 'jq' in the path"
+CAT="$(type -P cat)" || fail "Could not find 'cat' in the path"
 
 CLUSTER_ID="$("${BASEDIR}/rancher-get-cluster-id" "${CLUSTER_NAME}")" || exit 1
 RANCHER_API_ENDPOINT+="/${CLUSTER_ID}"
-PROJECT_ID="$("${CURL}" -fsSL -u "${RANCHER_TOKEN}" "${RANCHER_API_ENDPOINT}" | "${JQ}" -r ".data[] | select(.spec.displayName == \"${PROJECT_NAME}\") | .id")" || fail "Could not find the project named [${PROJECT_NAME}] in the ${CLUSTER_NAME} cluster"
+PROJECT_ID="$("${CURL}" -fsSL --config <(auth_params "${RANCHER_TOKEN}") "${RANCHER_API_ENDPOINT}" | "${JQ}" -r ".data[] | select(.spec.displayName == \"${PROJECT_NAME}\") | .id")" || fail "Could not find the project named [${PROJECT_NAME}] in the ${CLUSTER_NAME} cluster"
 echo "${PROJECT_ID}"
 exit 0
diff --git a/scripts/rancher-get-projects b/scripts/rancher-get-projects
--- a/scripts/rancher-get-projects
+++ b/scripts/rancher-get-projects
@@ -20,6 +20,24 @@ fail()
 	exit ${EXIT_CODE:-1}
 }
 
+auth_params()
+{
+	local USER="${1}"
+	local PASS=""
+
+	if [ ${#} -eq 1 ] ; then
+		[[ "${USER}" =~ ^([^:]*)(:(.*))?$ ]] || true
+		USER="${BASH_REMATCH[1]}"
+		PASS="${BASH_REMATCH[3]}"
+	else
+		PASS="${2}"
+	fi
+
+	"${CAT}" <<-EOF
+	user "${USER}:${PASS}"
+	EOF
+}
+
 usage()
 {
 	echo -e "usage: ${BASH_ARGV0:-${BASH_SOURCE:-${0}}} cluster-name"
@@ -50,10 +68,11 @@ CLUSTER_NAME="${1}"
 
 CURL="$(type -P curl)" || fail "Could not find 'curl' in the path"
 JQ="$(type -P jq)" || fail "Could not find 'jq' in the path"
+CAT="$(type -P cat)" || fail "Could not find 'cat' in the path"
 SORT="$(type -P sort)" || fail "Could not find 'sort' in the path"
 
 CLUSTER_ID="$("${BASEDIR}/rancher-get-cluster-id" "${CLUSTER_NAME}")" || exit 1
 RANCHER_API_ENDPOINT+="/${CLUSTER_ID}"
-LIST="$("${CURL}" -fsSL -u "${RANCHER_TOKEN}" "${RANCHER_API_ENDPOINT}" | "${JQ}" -r ".data[] | .id + \" \" + .spec.displayName")" || fail "Could not find the project listing in cluster ${CLUSTER_NAME}"
+LIST="$("${CURL}" -fsSL --config <(auth_params "${RANCHER_TOKEN}") "${RANCHER_API_ENDPOINT}" | "${JQ}" -r ".data[] | .id + \" \" + .spec.displayName")" || fail "Could not find the project listing in cluster ${CLUSTER_NAME}"
 echo "${LIST}" | "${SORT}" -k 2
 exit 0
diff --git a/scripts/rancher-list-clusters b/scripts/rancher-list-clusters
--- a/scripts/rancher-list-clusters
+++ b/scripts/rancher-list-clusters
@@ -20,6 +20,24 @@ fail()
 	exit ${EXIT_CODE:-1}
 }
 
+auth_params()
+{
+	local USER="${1}"
+	local PASS=""
+
+	if [ ${#} -eq 1 ] ; then
+		[[ "${USER}" =~ ^([^:]*)(:(.*))?$ ]] || true
+		USER="${BASH_REMATCH[1]}"
+		PASS="${BASH_REMATCH[3]}"
+	else
+		PASS="${2}"
+	fi
+
+	"${CAT}" <<-EOF
+	user "${USER}:${PASS}"
+	EOF
+}
+
 ADD_DESC="false"
 if [ ${#} -gt 0 ] ; then
 	case "${1,,}" in
@@ -36,6 +54,7 @@ fi
 
 CURL="$(type -P curl)" || fail "Could not find 'curl' in the path"
 JQ="$(type -P jq)" || fail "Could not find 'jq' in the path"
+CAT="$(type -P cat)" || fail "Could not find 'cat' in the path"
 SORT="$(type -P sort)" || fail "Could not find 'sort' in the path"
 
 #
@@ -47,4 +66,4 @@ SORT="$(type -P sort)" || fail "Could not find 'sort' in the path"
 QUERY=".data[] | .name"
 "${ADD_DESC}" && QUERY+=' + " " + .description'
 
-"${CURL}" -fsSL -u "${RANCHER_TOKEN}" "${RANCHER_API_ENDPOINT}" | "${JQ}" -r "${QUERY}" | "${SORT}"
+"${CURL}" -fsSL --config <(auth_params "${RANCHER_TOKEN}") "${RANCHER_API_ENDPOINT}" | "${JQ}" -r "${QUERY}" | "${SORT}"
