Don't wait for the results if the user doesn't want that

diff --git a/scripts/veracode-fetch-scan b/scripts/veracode-fetch-scan
--- a/scripts/veracode-fetch-scan
+++ b/scripts/veracode-fetch-scan
@@ -49,21 +49,30 @@ say "⚠️ Files will be stored in [${TARGET_PATH}]"
 BUILD_ID=()
 [ -z "${VERACODE_BUILD_ID}" ] || BUILD_ID=(-buildid "${VERACODE_BUILD_ID}")
 
+MIN_PROBE_SECONDS="30"
+DEF_PROBE_SECONDS="120"
 [ -v VERACODE_PROBE_SECONDS ] || VERACODE_PROBE_SECONDS=""
-[[ "${VERACODE_PROBE_SECONDS}" =~ ^[1-9][0-9]+$ ]] || VERACODE_PROBE_SECONDS="120"
+[[ "${VERACODE_PROBE_SECONDS}" =~ ^[1-9][0-9]*$ ]] || VERACODE_PROBE_SECONDS="${DEF_PROBE_SECONDS}"
+[ ${VERACODE_PROBE_SECONDS} -ge ${MIN_PROBE_SECONDS} ] || VERACODE_PROBE_SECONDS="${MIN_PROBE_SECONDS}"
 
+DEF_VERACODE_TIMEOUT="120"
 [ -v VERACODE_TIMEOUT ] || VERACODE_TIMEOUT=""
-[[ "${VERACODE_TIMEOUT}" =~ ^[1-9][0-9]+$ ]] || VERACODE_TIMEOUT="120"
+[[ "${VERACODE_TIMEOUT}" =~ ^(0|-?[1-9][0-9]*)$ ]] || VERACODE_TIMEOUT="${DEF_VERACODE_TIMEOUT}"
+
+[ ${VERACODE_TIMEOUT} -gt 0 ] || VERACODE_TIMEOUT=0
 
 # Compute the application ID based on the name
 APP_ID="$("${BASEDIR}/veracode-get-app-id" "${APP_NAME}")" || fail "Failed to get the application ID for [${APP_NAME}]"
 
 PROBE_START="$(date +%s)"
+TIMEOUT_SECONDS=$(( VERACODE_TIMEOUT * 60 ))
 while true ; do
 
 	# First things first!! Check the timeout!
-	PROBE_NOW="$(date +%s)"
-	[ $(( PROBE_NOW - PROBE_START )) -lt $(( VERACODE_TIMEOUT * 60 )) ] || fail "Timed out waiting for the scan to complete"
+	if [ ${TIMEOUT_SECONDS} -gt 0 ] ; then
+		REMAINING_SECONDS=$(( TIMEOUT_SECONDS - ( $(date +%s) - PROBE_START ) ))
+		[ ${REMAINING_SECONDS} -gt 0 ] || fail "Timed out waiting for the scan to complete"
+	fi
 
 	# No timeout? No problem!!
 	if [ -z "${VERACODE_BUILD_ID}" ] ; then
@@ -87,10 +96,16 @@ while true ; do
 	case "${STATUS^^}" in
 
 		# These are "failed" statuses
-		"INCOMPLETE" | "PRESCAN FAILED" | "NO MODULES DEFINED" ) fail "Cannot wait for results any longer" ;;
+		"INCOMPLETE" | "PRESCAN FAILED" | "NO MODULES DEFINED" ) fail "Cannot wait for results any longer (status = [${STATUS}])" ;;
 
 		# These are "waitable" statuses
 		"VENDOR CONFIRMATION" | "VENDOR REVIEWING" | "PRE-SCAN SUBMITTED" | "PRE-SCAN SUCCESS" | "SCAN IN PROCESS" )
+			[ ${TIMEOUT_SECONDS} -gt 0 ] || fail "The scan is still running (${STATUS}), and no wait timeout was specified - cannot continue"
+
+			# Use the lesser time between the number of seconds before we meet the timeout,
+			# and the configured number of seconds between each poll
+			[ ${REMAINING_SECONDS} -gt ${VERACODE_PROBE_SECONDS} ] || VERACODE_PROBE_SECONDS="${REMAINING_SECONDS}"
+
 			say "\t💤 The scan is still running, sleeping for ${VERACODE_PROBE_SECONDS} seconds before probing again"
 			sleep "${VERACODE_PROBE_SECONDS}" || fail "Sleep interrupted, cannot continue"
 			continue
